### ISSUE TITLE
Add simple AnnData -> Pandas DF and Pandas DF -> AnnData

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#137]
When wrangling with data it might be easier to first work with a Pandas object and to then transform it into an AnnData object. 
A part of the reasoning for this is that it is very difficult to get an overview of the values stored in X together with their headers. We could either improve this or try to support the easy transformation between the two formats.

**Comment by Imipenem** [comment]
> https://anndata.readthedocs.io/en/latest/anndata.AnnData.to_df.html
> 
> This actually exists!

I think we have to adapt this for our data though (for example datetime data is obs only, what to do with encoded data etc.)

**Comment by Zethson** [comment]
> encoded data

Think we can just keep that. Would not add any special cases for this.

> datetime data is obs only

Good point. Don't think that we should automatically append all `obs` columns to X and then transform to a DF. I'd suggest that we simply parameterize this initially for both directions. Basically a parameter `obs_columns` for AnnData -> DataFrame and the usual `obs_only` for DataFrame -> AnnData
