### ISSUE TITLE
Add function to move data from X to obs and vice versa

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#151]
Would be very useful to have a method to move data from X to obs and the other way around. I am sure that when loading complex data one sometimes forgets to add a column to "obs_only" and instead of loading the complete (large) file again it would help to just move columns.

**Comment by ivirshup** [comment]
Could you propose an API here? Also, I imagine `obsm`, `var`, and `varm` would be good destinations too?

**Comment by Zethson** [comment]
> Could you propose an API here? Also, I imagine `obsm`, `var`, and `varm` would be good destinations too?

Yes, to all. We'll discuss.

**Comment by ivirshup** [comment]
<details>
<summary> Drafts in case you want to play around with the API: </summary>

```python
from typing import Union

import anndata as ad, numpy as np, pandas as pd

def split_out(adata: ad.AnnData, idx: "np.ndarray[1, bool]", *, axis=1):
    idxs = [slice(None), slice(None)]
    idxs[axis] = idx
    idxs = tuple(idxs)
    df = adata[idxs].to_df()
    if axis == 1:
        adata._inplace_subset_var(~idx)
        adata.obs = adata.obs.join(df)
    elif axis == 0:
        adata._inplace_subset_obs(~idx)
        adata.var = adata.var.join(df)


def splice_in(
        adata: ad.AnnData,
        *,
        obs: Union[str, list[str]]=None,
        var: Union[str, list[str]]=None,
    ) -> ad.AnnData:
    assert (obs is None) + (var is None) == 1
    if obs is not None:
        if isinstance(obs, str): obs = [obs]
        res = ad.concat([adata, ad.AnnData(adata.var[obs])], axis=0)
        res.var.drop(columns=obs, inplace=True)
        return res
    elif var is not None:
        if isinstance(var, str): var = [var]
        res = ad.concat([adata, ad.AnnData(adata.obs[var])], axis=1)
        res.obs.drop(columns=var, inplace=True)
        return res


from anndata.tests.helpers import gen_adata

a = gen_adata((20, 10))
b = gen_adata((20, 5))
c = ad.concat({"a": a, "b": b}, axis=1, index_unique="-", label="vartype")
d = c.copy()
d
```

```
AnnData object with n_obs × n_vars = 20 × 15
    var: 'var_cat', 'cat_ordered', 'int64', 'float64', 'uint8', 'vartype'
    varm: 'array', 'sparse', 'df'
    layers: 'array', 'sparse'
```

```python
removed_var = c.var_names[c.var["vartype"] == "b"]

split_out(d, d.var_names.isin(removed_var))  # convert removed_var to mask
d
```

```
AnnData object with n_obs × n_vars = 20 × 10
    obs: 'gene0-b', 'gene1-b', 'gene2-b', 'gene3-b', 'gene4-b'
    var: 'var_cat', 'cat_ordered', 'int64', 'float64', 'uint8', 'vartype'
    varm: 'array', 'sparse', 'df'
    layers: 'array', 'sparse'
```

```python
splice_in(d, var=removed_var)
```

```
AnnData object with n_obs × n_vars = 20 × 15
```

</details>

**Comment by Imipenem** [comment]
@ivirshup I'm currently implementing this for ehrapy.
I like your solution (which I altered a bit, but basically the same function calls) to move some columns from `obs` to `X`:
```
# some setup code here
   elif var is not None:
        if isinstance(var, str): var = [var]
        res = ad.concat([adata, ad.AnnData(adata.obs[var])], axis=1) # this is where the error occurs
        res.obs.drop(columns=var, inplace=True)
```

However, for ehrapy, we need this to work with multiple datatypes and not only `numeric dtypes`, since otherwise such a function call would require the input `AnnData` object to be already encoded (or allow moving numerical or encoded columns only to X from obs).
But `concat` fails to do so (I guess it was never meant to be used in this way), because it calls `_init_as_actual` without the possibility to specify the `dtype` for the new `AnnData` object (for example via `kwargs`).

Can u see an easy way here to fix this? Or, if we want such behaviour, do we have to write our own custom `concat` function?

@Zethson : Should we generally even allow a situation like this (moving some non-numerical dtype columns from `obs` to `X`)? Or, whenever a user tries to call it like this, internally encode the input, if its not numerical, to ensure a "numerical" `X`?

**Comment by ivirshup** [comment]
What would you want the `dtype` to be? 

This made me realize there was a bug in concat, and that it should try to keep the casting of `dtypes`, which I solved [here](https://github.com/theislab/anndata/pull/551/commits/b45532da7ae588f9be9d84f40b3ac69592322cdd).  Does that change fix your issue?

**Comment by Imipenem** [comment]
Thanks for the fast response. First look, this should solve the issue, will try this out tomorrow, but I'm pretty sure this should fix it.

**Comment by Imipenem** [comment]
Tested and it worked, nice. Thanks again.

**Comment by ivirshup** [comment]
Could you share a snippet? Ideally something I could run, but `repr`s of input, the `concat` call, and `repr`s of output could do for a quick check.

**Comment by Imipenem** [comment]
Sure, sorry forgot to add.

```
from anndata import AnnData, concat
import numpy as np
import pandas as pd
from typing import Union, List

def move_to_x(adata: AnnData, to_x: List[str]) -> AnnData:
    new_adata = concat([adata, AnnData(adata.obs[to_x], dtype="object")], axis=1)

    return new_adata


if __name__ == "__main__":
    x = np.array([["str"+str(i) for i in range(3)], [True, False, False]], dtype="object").transpose()
    adata = AnnData(X=x, obs=pd.DataFrame({"date": ["12:07", "12:08", "12:09"], "intcol": [i for i in range(3)]}), var=pd.DataFrame(index=["strcol", "boolcol"]), dtype="object")
    res = move_to_x(adata, ["intcol"])

    print(res)
    print(res.X)
    print(res.obs)
```

**Comment by ivirshup** [comment]
You can control how elements along the axis not being concatenated are combined with the `merge` argument. It defaults to `None`, which is fast and conservative by keeping nothing. You may want the behavior of `"unique"` or `"only"` here:

```python
In [22]: adata = AnnData(
    ...:     X=np.array([["str"+str(i) for i in range(3)], [True, False, False]], dtype="object").transpose(),
    ...:     obs=pd.DataFrame({"date": ["12:07", "12:08", "12:09"], "intcol": [i for i in range(3)]}),
    ...:     var=pd.DataFrame(index=["strcol", "boolcol"]),
    ...:     dtype=object,
    ...: )

In [23]: concat([adata, AnnData(adata.obs[["intcol"]], dtype="object")], axis=1)
Out[23]: AnnData object with n_obs × n_vars = 3 × 3

In [24]: concat([adata, AnnData(adata.obs[["intcol"]], dtype="object")], axis=1, merge="unique")
Out[24]: 
AnnData object with n_obs × n_vars = 3 × 3
    obs: 'date', 'intcol'

**Comment by Imipenem** [comment]
Nice, thanks again.

**Comment by Imipenem** [comment]
Follow up question arised: Do you know whether its possible to **only** keep those, that were not passed to the second object (here: `intcol`, so I only want to keep `date` in the resulting `obs`)?
Currently, I just slice them out after concatenating.
