### ISSUE TITLE
Caching fails when writing NANs to cache file

### ISSUE THREAD

**Issue by Imipenem** [theislab/ehrapy#172]
**Describe the bug**

When using `cache=True` in read function and there are NANs in non-numeric columns, writing to the cache file fails: `TypeError: Can't implicitly convert non-string objects to strings`. This happens not because of the encoder does not encodes it in X (it does). But we need to store the original values somewhere (uns in our case), and those nan values will be stored there too.

**To Reproduce**

1. Get a .csv file with some numerical and non-numerical columns (and non numerical columns misses at least one value)
2. Run `read('my_file_path', cache=True)`
3. See error

**Expected behavior**

Cache should work.

**Possible solution**
I'm not quite sure, what's the way to go here.
One solution would be replace like all `nan` in the original values with like `""` or something (just an empty string) and cast it back while reading from the cache file.

Any ideas here @Zethson ?

**Comment by Zethson** [comment]
`One solution would be replace like all nan in the original values with like "" or something (just an empty string) and cast it back while reading from the cache file.`

Since we are handling such edge cases anyways I think this should be fine?

**Comment by Imipenem** [comment]
> `One solution would be replace like all nan in the original values with like "" or something (just an empty string) and cast it back while reading from the cache file.`
> 
> Since we are handling such edge cases anyways I think this should be fine?

Yeah, I mean would be just a "hidden" step of Data imputation. I mean when writing, the user won't notify this at all.
But what what about when reading. Do we need to "cast" it back, or just "leave it as it is", sine this step would be required anyways later on?

**Comment by Zethson** [comment]
> > `One solution would be replace like all nan in the original values with like "" or something (just an empty string) and cast it back while reading from the cache file.`
> > Since we are handling such edge cases anyways I think this should be fine?
> 
> Yeah, I mean would be just a "hidden" step of Data imputation. I mean when writing, the user won't notify this at all. But what what about when reading. Do we need to "cast" it back, or just "leave it as it is", sine this step would be required anyways later on?

Think we have to go with casting back to NaNs. They user may decide to impute the strings and not leave them as empty strings. Agree?

**Comment by Imipenem** [comment]
What about just treating empty strings as nans? Regarding imputation etc.?
