### ISSUE TITLE
Error with click v8.0.3

### ISSUE THREAD

**Issue by lazappi** [theislab/ehrapy#176]
**Describe the bug**

I was getting this error when importing **ehrapy**

```python
ModuleNotFoundError: No module named 'click._bashcomplete'
```

A bit of googling seemed to suggest this might be an issue with newer versions of **click**. Downgrading to v7.1.2 seemed to fix it.

**To Reproduce**

Import **ehrapy** with **click** v8.0.3 installed

**Expected behavior**

Successful import with no error

**System [please complete the following information]:**

-   OS: MacOS 10.15
-   Language Version: Python 3.8
-   Virtual environment: conda

**Additional context**

Possibly (probably) I'm just doing something wrong but thought I would raise it just in case

**Comment by Zethson** [comment]
Thanks for reporting. We can restrict click to 7 < 8 versions, but I think that we may have resolved this already on development. Will check.

**Comment by Zethson** [comment]
Closed because I cannot reproduce it. We should test this with a wheel later...
