### ISSUE TITLE
Encoding fails if there is no "original" layer

### ISSUE THREAD

**Issue by lazappi** [theislab/ehrapy#177]
**Describe the bug**

If the AnnData object is created by `ehrapy.io.read` a layer called "original" is added. The encoding function assumes this is present and fails with an unclear error if it isn't. 

**To Reproduce**

```python
from anndata import AnnData
import ehrapy

X = np.array([[1, 3.4, "A string", "A different string"], [2, 5.4, "Silly string", "A different string"], [2, 5.7, "A string", "What string?"]], dtype=np.dtype(object))
adata = AnnData(X=X_strings, dtype=np.dtype(object))

# Encoding fails
ehrapy.preprocessing.encode(adata, autodetect=True)
KeyError: 'original'

# If we add "original" first it works
adata.layers["original"] = adata.X.copy()
ehrapy.preprocessing.encode(adata, autodetect=True)
AnnData object with n_obs × n_vars = 3 × 4
    obs: '2', '3'
    uns: 'categoricals', 'original_values_categoricals', 'current_encodings'
    layers: 'original'
```

**Expected behavior**

Either the "original" layer is created automatically or a clearer error saying that it is missing and how to add it

**System [please complete the following information]:**

-   OS: MacOS 10.15
-   Language Version: Python 3.8
-   Virtual environment: Conda

**Comment by Zethson** [comment]
@Imipenem this one is for today :)

**Comment by Imipenem** [comment]
@Zethson 
I'm not sure whether, in this case, it should be really created automatically or not (error, but with a clearer error message). 
This layer keeps the original values and is created automatically while using `read`  as mentioned. 
But then, there is a chance the data (or `X` at least) was modified, which
won`t be reflected in this layer. 

When not using read, IMO, even if we create it automatically, we should maybe throw a warning that explains this?

**Comment by Zethson** [comment]
As discussed we will simply copy stuff to originals if it does not yet exist.
