### ISSUE TITLE
Object state check decorator

### ISSUE THREAD

**Issue by Imipenem** [theislab/ehrapy#182]
**Is your feature request related to a problem? Please describe.**

When using ehrapy, it's useful to keep some sort of reasonable order in what to do first after reading an input dataset.

**For example:**

- When dealing with freetext in the dataset, it would be very useful (not to say required) to use medcat, in order to reduce stored  boilerplate text and extract the key components for each text (for example group diagnoses together) and then encode only those important components and not the rest.

- Before running any algorithms on the `AnnData` object (or a collection of them), `X` should only contain numerical values (so all previously non-numerical values should be encoded).

Since there are a few of those requirements, even when they are well documented, it could be easily overseen by users and lead to strange bugs and issues.

**Describe the solution you would like**

In order to solve this issue (and also help to reduce development effort) the implementation of a nice `"check_requirements"` (or similar) decorator would be good, which can then be used for every algorithm function call. This would, in case of an error, also generate a much clearer error message for the user, what went wrong and how to fix it.

Any more ideas for requirements that should be met @Zethson?

**Comment by Zethson** [comment]
LGTM! Let's implement this.

**Comment by Imipenem** [comment]
As discussed; Guess we won't need this currently (maybe in the future). Closing this for now.
