### ISSUE TITLE
Windows tests failing because ghostscript cannot be found

### ISSUE THREAD

**Issue by Imipenem** [theislab/ehrapy#195]
**Describe the bug**

Tests workflow on windows currently fail, cause _ghostscript_ (which is needed for pdf parsing) cannot be found, altough its correctly installed.

See: https://stackoverflow.com/questions/53319099/python-camelot-error-ghostscriptnotfound-while-it-is-installed, maybe some solutions here can fix this for the workflow.

Used workflow syntax (_ghostscript 9.55.0_ gets installed but somehow not recognized):

```
- name: Install ghostscript windows
              if: matrix.os == 'windows-latest'
              run: |
                  choco install ghostscript
                  set PATH=%PATH%;"C:\Program Files\gs\gs9.55\bin";"C:\Program Files\gs\gs9.55\lib"
```

**Comment by Zethson** [comment]
https://github.com/theislab/ehrapy/pull/196
