### ISSUE TITLE
Rename encoding uns keys

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#214]
Currently they are named

`uns: 'categoricals_encoded_with_mode', 'original_values_categoricals', 'current_encodings'`

I am not really happy with `categoricals_encoded_with_mode` and `current_encodings`.

```
adata.uns["categoricals_encoded_with_mode"]
{'one_hot_encoding': ['service_unit', 'day_icu_intime']}
```

This is encoding to column. 

```
adata.uns["current_encodings"]
{'service_unit': 'one_hot_encoding', 'day_icu_intime': 'one_hot_encoding'}
```

This is column to encoding.

Let's name them accordingly.

**Comment by Zethson** [comment]
Thoughts @Imipenem ?

**Comment by Imipenem** [comment]
Imo `current_encodings` is fine, since its what it claims to be: The current encoding mode for each encoded var. 

But yeah `categoricals_encoded_with_mode` is not that great and should be replaced. Lets talk about this later.
