### ISSUE TITLE
Add heart failure dataset

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#228]
http://archive.ics.uci.edu/ml/datasets/Heart+failure+clinical+records

This is also a good one.

**Comment by amisharin** [comment]
https://www.nature.com/articles/s41551-020-00633-5 
http://ictcf.biocuckoo.cn

What about this one for pneumonia? No time-series data, but still could be useful.

**Comment by Zethson** [comment]
@amisharin great resource! Unfortunately the clinical features are in a broken format, but I will figure this out with the authors.

Thank you.

**Comment by amisharin** [comment]
consider this one for ICU data: https://eicu-crd.mit.edu/about/eicu/ (somewhat similar to MIMIC, but non-overlapping).

**Comment by Zethson** [comment]
> consider this one for ICU data: https://eicu-crd.mit.edu/about/eicu/ (somewhat similar to MIMIC, but non-overlapping).

Yeah, this one will certainly be added. However, just like the MIMIC ones, it is not 100% publicly accessible because you need access to Physionet. 
Nevertheless, we can make access a little bit easier :)
Thanks.
