### ISSUE TITLE
Categoricals only stored if `autodetect=True` when encoding

### ISSUE THREAD

**Issue by lazappi** [theislab/ehrapy#262]
**Describe the bug**

The `adata.uns["categoricals"]` field is only set when `autodetect=True` during encoding. This is important because we use this field to check an object has been encoded and identify numeric variables for normalization in #162.

**To Reproduce**

Example with MIMIC-II

```python
adata = ep.dt.mimic_2(encoded=False)
adata = ep.pp.encode(
    adata, encodings={"one_hot_encoding": ["service_unit", "day_icu_intime"]}
)
"categoricals" in adata.uns_keys()
```

**Expected behavior**

Either need to make sure this is always set or have another system for identifying numeric variables.

**System [please complete the following information]:**

-   OS: MacOS
-   Language Version: Python 3.8
-   Virtual environment: conda

**Comment by Zethson** [comment]
Thanks! Putting into urgent 0.1 milestone.

**Comment by Imipenem** [comment]
IMO, we should have another way of detecting numerical data in the `AnnData` object. Setting this property always makes no sense, because when not using `autodetect` ehrapy already knows the `categorical` values (those that were passed).

**Comment by Zethson** [comment]
What is a good alternative?  Friday, 21 January 2022, 06:36PM +01:00 from Philipp Ehmele  ***@***.*** :

**Comment by Imipenem** [comment]
One thing that comes to my mind would be to just use a heuristic approach: 
Something like:
```
for each variable in var:
    take first x non nan values
    infer dtype of those values
    if numerical:
        add to to result
```
Other solution: When reading our data, just store all numerical values in a list/set and store it somewhere. Since we currently always transform pandas dataframes to anndata object, this could be easier, since its very easy (in contrast to a numpy array, that is not designed for this) to get the dtype for each column.

**Comment by Zethson** [comment]
Nice.

Option 1. Totally not a fan. Ugly and requires computation. A colleague of mine has a dataset with easily more than 2000 features already.

Option 2. Fine with me.

Option 3. I don't see how this gives us what we want?

**Comment by Imipenem** [comment]
> Option 3. I don't see how this gives us what we want?

;D. I mean for each column, if there's any `NaN` value (any non numerical value) it will return true; when it return false all values in the column are numerical; it's that simple.

**Comment by Zethson** [comment]
> > Option 3. I don't see how this gives us what we want?
> 
> ;D. I mean for each column, if there's any `NaN` value (any non numerical value) it will return true; when it return false all values in the column are numerical; it's that simple.

Yeah, but we would have to calculate this every time. Too expensive.
Let's find a solution which is simply stored in `.uns`

**Comment by Imipenem** [comment]
Na its a pretty fast operation. I just want to point out of different ways cause I have the feeling we always tend to just store everything into uns...
