### ISSUE TITLE
Implement SNOWMED-CT mapping 

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#264]
https://owlready2.readthedocs.io/en/latest/pymedtermino2.html

**Comment by Zethson** [comment]
Also need the ability to convert from ICD9 to 10 and vice versa.

**Comment by Imipenem** [comment]
> Also need the ability to convert from ICD9 to 10 and vice versa.


ICD 9 is pretty outdated by time. Is there any real world data you're aware of that uses ICD-9?

**Comment by Zethson** [comment]
> > Also need the ability to convert from ICD9 to 10 and vice versa.
> 
> ICD 9 is pretty outdated by time. Is there any real world data you're aware of that uses ICD-9?

https://www.nature.com/articles/s41746-020-0301-z

They mapped back the ICD10 to ICD9. Don't ask me why, but apparently people do this? This is why I wrote this in the first place :)

**Comment by Imipenem** [comment]
Guess this is due to the fact l, that they collected data from like 1980-2016 (For example, in Germany ICD 9 has been replaced by ICD 10 in 1998). Even ICD 10 is outdated by now (ICD-11 is latest standard since 1.1.2022).

I'm not a big fan of converting between different ICD versions (for example, there are many new diagnosis especially F-diagnosis that are new in ICD 11 (or changed)).

**Comment by Zethson** [comment]
> Guess this is due to the fact l, that they collected data from like 1980-2016 (For example, in Germany ICD 9 has been replaced by ICD 10 in 1998). Even ICD 10 is outdated by now (ICD-11 is latest standard since 1.1.2022).
> 
> I'm not a big fan of converting between different ICD versions (for example, there are many new diagnosis especially F-diagnosis that are new in ICD 11 (or changed)).

Thank you for the explanation. But wouldn't it then be beneficial to allow for ICD 10 to 11 mappings? I think that a major reason why I think that this is important is that when you want to merge different data sets from different sources it is required that they use the same ICD nomenclature.

**Comment by Imipenem** [comment]
> But wouldn't it then be beneficial to allow for ICD 10 to 11 mappings?

Yes, I mean there is like a 5 year period where ICD-10 is still allowed, before moving to ICD-11, but since most of data will be still ICD-10, this could be beneficial.

**Comment by Zethson** [comment]
Closing in favor of Bionty
