### ISSUE TITLE
Give user feedback how many values were imputed

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#267]
Maybe even for every feature or so.
Some feedback would be useful.

**Comment by Imipenem** [comment]
> How many values

Isn't there already a function in qc which plots how many missing values were there per column?

**Comment by Zethson** [comment]
> > How many values
> 
> Isn't there already a function in qc which plots how many missing values were there per column?

Yes there is. Possible to compute it twice and give a diff.

**Comment by Imipenem** [comment]
Hmm, I mean impute will always impute every missing value in a column anyways.

**Comment by Zethson** [comment]
> Hmm, I mean impute will always impute every missing value in a column anyways.

Of course. But would be nice to have user feedback like:

"Imputed 560 values for age and 120 for BMI" or whatever.

**Comment by Imipenem** [comment]
> "Imputed 560 values for age and 120 for BMI" or whatever.

With an optional plot (so basically reuse the QC function?) 
Guess for more columns a plot could be easier to read. Alternatively a nice rich table?

**Comment by Zethson** [comment]
> > "Imputed 560 values for age and 120 for BMI" or whatever.
> 
> With an optional plot (so basically reuse the QC function?) Guess for more columns a plot could be easier to read. Alternatively a nice rich table?

Wouldn't make it this fancy.

Doing this with scanpy usually gives feedback like:

```
... storing 'service_unit' as categorical
... storing 'day_icu_intime' as categorical
```

(We need to do this as well #246)

I could see it happening like:

```
... imputed 560 values in 'age'
... imputed 249 values in 'bmi'
```

This output could be optional.

**Comment by Imipenem** [comment]
Hmm, personally I dont like this because it gets out of hand with just a few columns. 
Optional of course, but I think it would benefit from a nice layout within a table. 

(For your first example, the print statements are enough IMO).

**Comment by Zethson** [comment]
We decided to print out warnings when more than 30% (can be a parameter) of the values of a column had to be imputed. Can use the QC information for this.
