### ISSUE TITLE
Normalization with an object that never required encoding fails

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#273]
![image](https://user-images.githubusercontent.com/21954664/150793313-13e681c0-bc36-452a-9363-15fe1c8989f9.png)

I suspect that @amitfrish never had to encode any of his features and therefore the required fields in `.uns` to differ between numerical and categorical values fails.

We have to find a solution for this.

**Comment by Imipenem** [comment]
Hm it should not. My suspicion is that the assert statement is simply too strict here. The entries in `uns` are not related to encoding since they are set while reading.

**Comment by Zethson** [comment]
```
def assert_encoded(adata: AnnData):
    try:
        assert any(enc_flag in adata.uns_keys() for enc_flag in ["categoricals", "encoding_to_var"])
    except AssertionError:
        raise NotEncodedError("The AnnData object has not yet been encoded.") from AssertionError
```

**Comment by Zethson** [comment]
I guess that it fails because categoricals does not exist?

**Comment by Zethson** [comment]
Quick fix idea by @Imipenem : Check that dtype of X is float32 or other numerical.
