### ISSUE TITLE
MIMIC-III datetime detection not working?

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#274]
Not sure, but CI fails. Didn't before changes from yday.

**Comment by Imipenem** [comment]
The mimic-II dataset has datetimes? 😄

**Comment by Zethson** [comment]
Title fixed :) MIMIC-III

**Comment by Imipenem** [comment]
Hmm, don't know why this should be the case. I tested it using some of my custom test files and a subset of the MIMIC-III dataset and it worked well.

IMO, we did not introduced changes to that lately anyways.

**Comment by Zethson** [comment]
Well, CI is failing. Repeatedly.

**Comment by Zethson** [comment]
`KeyError: 'storetime'`

**Comment by Zethson** [comment]
Looking into it

**Comment by Imipenem** [comment]
That's not related to datetime detection. I know where this is coming from: We detect `non_numerical` and `numerical` columns BEFORE they are moved to obs. So they pretend to be non numerical columns in `X` but they are moved to `obs`. That's not how it should be. Will fix.

**Comment by Zethson** [comment]
Thanks!  Monday, 24 January 2022, 07:38PM +01:00 from Philipp Ehmele  ***@***.*** :

**Comment by Imipenem** [comment]
Well, reverting my comment from above: We do this indeed, I just used the wrong variable..., so it's a simple fix^^
