### ISSUE TITLE
Specify encoding mode when autodetect=True

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#287]
**Is your feature request related to a problem? Please describe.**

`adata=ep.pp.encode(adata,autodetect=True)`

Currently simply label encodes all autodetected columns.

**Describe the solution you would like**

`adata=ep.pp.encode(adata,autodetect=True, encodings="one-hot")` which one-hot encodes all detected columns.

**Comment by Imipenem** [comment]
This should be restricted tough to `one-hot, label` and `count`, since those won't need any additional information (for example `hash-encoding` would require the specification of buckets and since the encoded columns are unknown previously it won't be possible).

**Comment by Zethson** [comment]
Agree. Need to throw appropriate errors if this expectation is not met.
