### ISSUE TITLE
Profile ehrapy

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#293]
Let's collect tools and ideas to profile ehrapy here.

Guess https://github.com/plasma-umass/scalene should be good.

**Comment by Imipenem** [comment]
https://pyinstrument.readthedocs.io/en/latest/home.html

Seems like a nice, lightweight profiler.

**Comment by Zethson** [comment]
> Maybe we could also setup a new repo containing a few profile scripts and data, so when adding new features we always profile with the same data etc.

Yeah, I like this. Let's not create it in theislab, but private for now.

**Comment by Imipenem** [comment]
https://github.com/benfred/py-spy

Gonna start with this one. The Flame graphs actually look promising. Created a repo as discussed and uploaded first results for IO part.
