### ISSUE TITLE
Extend configurability of anndata_to_df

### ISSUE THREAD

**Issue by Imipenem** [theislab/ehrapy#302]
**Is your feature request related to a problem? Please describe.**

IMO we should provide more possibilities for the user to craft a "custom" dataframe. 

Especially: what happens with values in `uns, var or obs`? Users should be able to include those (or subsets) into the resulting dataframe or only add specific keys. Not necessarily, but this would give the user more flexibility. 

**Describe the solution you would like**

See above.

**Comment by Zethson** [comment]
Let's discuss this.
What you are suggesting is that people could for example append var or obs to X which would then result in the new Pandas DataFrame?

**Comment by Imipenem** [comment]
> What you are suggesting is that people could for example append var or obs to X which would then result in the new Pandas DataFrame? As an option of course.

Yes, that's what I had in mind.

**Comment by Zethson** [comment]
We now have support for obs and var. IMO adding anything from obsm, varm or uns (this one is debatable) is a bit of a stretch. 

I think that we want people to only use the option from AnnData to pd.df early for data wrangling but not very late. It's fine if it's incomplete. Just like the actual AnnData implementation.

**Comment by Zethson** [comment]
Added support for layers as well
