### ISSUE TITLE
df_to_anndata only looks for indices in the columns, but not the actual index

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#305]
df_to_anndata fails when trying to supply the actual index of a Pandas DataFrame and not one of the columns as `index_column`.
Kind of a bug, but also a feature request :)

**Comment by Zethson** [comment]
Would also appreciate this to be in the test coverage.

**Comment by Imipenem** [comment]
I had this implemented originally but I removed it somewhere down the road, cause it got a bit complex with lots of `if ... else ...` stuff. Will have another look at it.

**Comment by Imipenem** [comment]
Hm are you sure about this one? I just tried it and it worked out of the box. @Zethson

**Comment by Imipenem** [comment]
> df.index.set_names('quarter')

Btw, this should be either `df = df.index.set_names('quarter')` or `df.index.set_names('quarter', inplace=True)`
