### ISSUE TITLE
type_overview improvements

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#306]
Really useful functions.

Couple of suggestions

1. move to anndata extensions
2. add parameter to sort the output by data type -> first floats, then booleans and then strings last or something
3. Variable names for AnnData object with 173 vars and 82 obs  - Variable names for AnnData object with 82 obs and 173 vars

**Comment by Imipenem** [comment]
4. add an option to somehow display `uns` summary
5.  sort by encoding mode
