### ISSUE TITLE
Better support for 0 and 1 categoricals

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#314]
Unfortunately, many datasets use 0 and 1 for booleans in columns. These must be autodetected as categoricals and also need to be e.g. one-hot encoded when requested.

What do we do when columns have 0, 1 and 2 for example? Are these already detected in the current implementation @Imipenem ?

**Comment by Imipenem** [comment]
I guess  0 and 1 are common representations for booleans and might be detected as such by pandas. 


0,1 and 2 are counted as numericals, but that's an endless topic, like: What about 0,1,2,3 or 3-15 (some scores like GCS use this scala). 
We can try to detect such columns, but therefore we also provide the custom encodings besides autodetect.

**Comment by Zethson** [comment]
> 0,1 and 2 are counted as numericals, but that's an endless topic, like: What about 0,1,2,3 or 3-15 (some scores like GCS use this scala). We can try to detect such columns, but therefore we also provide the custom encodings besides autodetect.

Totally get what you're saying. Then I guess this should still not be autodetected and users would have to custom encode this. But the column would be numerical, right? Does this work with out encoding currently?

**Comment by Imipenem** [comment]
> But the column would be numerical, right? Does this work with out encoding currently?

The original column would be numerical (after encoding as well).

**Comment by Zethson** [comment]
As discussed, we need an autodetection for these as well.
