### ISSUE TITLE
Writing unencoded dataset results in error

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#333]
Dataset: https://physionet.org/content/mimiciii-demo/1.4/LABEVENTS.csv
```
adata = ep.io.read(folder+"LABEVENTS.csv", delimiter=',', index_column=0, columns_obs_only=["subject_id","itemid","charttime","valueuom"])
ep.pp.knn_impute(adata)
```

Writing to h5ad then results into 
````
TypeError: Can't implicitly convert non-string objects to strings
```

I thought it would still just temporarily label encode it and write it out?

**Comment by Zethson** [comment]
> The implicit encoding currently only happens when using `cache=True` in `read`.

So how can we improve this situation here? A better error message? Can the new AnnData version write this?

**Comment by Imipenem** [comment]
How did you call the `write` function?

**Comment by Zethson** [comment]
> How did you call the `write` function? And can you paste the whole traceback?
> 
> Looking at the code, I identified two main problems:
> 
>     * The check for an unencoded AnnData object produces false negatives.
> 
>     * This check only works when extension is not `.csv`.

@amitfrish can you help here with the details, please?

**Comment by Imipenem** [comment]
Tried to reproduce the error above, but I got our custom error instead (which is intended currently, when trying to write an AnnData object with non numerical values and unencoded).

**Comment by amitfrish** [comment]
Sure,
You can see my code in: /storage/groups/ml01/workspace/amit.frishberg/TimeAxInEhrapy/runRTimeAx.ipynb
Just remove the encode function and try to write it.
