### ISSUE TITLE
Unable to write Diabetes 130 dataset

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#337]
**Describe the bug**

╭──────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ```
─────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                                                            │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_io/utils.py:209 in func_wrapper                                                                                     │
│                                                                                                                                                                                            │
│   206 │   @wraps(func)                                                                                                                                                                     │
│   207 │   def func_wrapper(elem, key, val, *args, **kwargs):                                                                                                                               │
│   208 │   │   try:                                                                                                                                                                         │
│ ❱ 209 │   │   │   return func(elem, key, val, *args, **kwargs)                                                                                                                             │
│   210 │   │   except Exception as e:                                                                                                                                                       │
│   211 │   │   │   parent = _get_parent(elem)                                                                                                                                               │
│   212 │   │   │   raise type(e)(                                                                                                                                                           │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_io/h5ad.py:270 in write_series                                                                                      │
│                                                                                                                                                                                            │
│   267 def write_series(group, key, series, dataset_kwargs=MappingProxyType({})):                                                                                                           │
│   268 │   # group here is an h5py type, otherwise categoricals won’t write                                                                                                                 │
│   269 │   if series.dtype == object:  # Assuming it’s string                                                                                                                               │
│ ❱ 270 │   │   group.create_dataset(                                                                                                                                                        │
│   271 │   │   │   key,                                                                                                                                                                     │
│   272 │   │   │   data=series.values,                                                                                                                                                      │
│   273 │   │   │   dtype=h5py.special_dtype(vlen=str),                                                                                                                                      │
│                                                                                                                                                                                            │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/h5py/_hl/group.py:149 in create_dataset                                                                                      │
│                                                                                                                                                                                            │
│   146 │   │   │   │   │   parent_path, name = name.rsplit(b'/', 1)                                                                                                                         │
│   147 │   │   │   │   │   group = self.require_group(parent_path)                                                                                                                          │
│   148 │   │   │                                                                                                                                                                            │
│ ❱ 149 │   │   │   dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)                                                                                                    │
│   150 │   │   │   dset = dataset.Dataset(dsid)                                                                                                                                             │
│   151 │   │   │   return dset                                                                                                                                                              │
│   152                                                                                                                                                                                      │
│                                                                                                                                                                                            │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/h5py/_hl/dataset.py:145 in make_new_dset                                                                                     │
│                                                                                                                                                                                            │
│    142 │   dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl)                                                                                                                      │
│    143 │                                                                                                                                                                                   │
│    144 │   if (data is not None) and (not isinstance(data, Empty)):                                                                                                                        │
│ ❱  145 │   │   dset_id.write(h5s.ALL, h5s.ALL, data)                                                                                                                                       │
│    146 │                                                                                                                                                                                   │
│    147 │   return dset_id                                                                                                                                                                  │
│    148                                                                                                                                                                                     │
│                                                                                                                                                                                            │
│ /home/zeth/PycharmProjects/CellVGAE/example_data/h5py/_objects.pyx:54 in h5py._objects.with_phil.wrapper                                                                                   │
│                                                                                                                                                                                            │
│ [Errno 2] No such file or directory: '/home/zeth/PycharmProjects/CellVGAE/example_data/h5py/_objects.pyx'                                                                                  │
│                                                                                                                                                                                            │
│ /home/zeth/PycharmProjects/CellVGAE/example_data/h5py/_objects.pyx:55 in h5py._objects.with_phil.wrapper                                                                                   │
│                                                                                                                                                                                            │
│ [Errno 2] No such file or directory: '/home/zeth/PycharmProjects/CellVGAE/example_data/h5py/_objects.pyx'                                                                                  │
│                                                                                                                                                                                            │
│ /home/zeth/PycharmProjects/CellVGAE/example_data/h5py/h5d.pyx:232 in h5py.h5d.DatasetID.write                                                                                              │
│                                                                                                                                                                                            │
│ [Errno 2] No such file or directory: '/home/zeth/PycharmProjects/CellVGAE/example_data/h5py/h5d.pyx'                                                                                       │
│                                                                                                                                                                                            │
│ /home/zeth/PycharmProjects/CellVGAE/example_data/h5py/_proxy.pyx:145 in h5py._proxy.dset_rw                                                                                                │
│                                                                                                                                                                                            │
│ [Errno 2] No such file or directory: '/home/zeth/PycharmProjects/CellVGAE/example_data/h5py/_proxy.pyx'                                                                                    │
│                                                                                                                                                                                            │
│ /home/zeth/PycharmProjects/CellVGAE/example_data/h5py/_conv.pyx:444 in h5py._conv.str2vlen                                                                                                 │
│                                                                                                                                                                                            │
│ [Errno 2] No such file or directory: '/home/zeth/PycharmProjects/CellVGAE/example_data/h5py/_conv.pyx'                                                                                     │
│                                                                                                                                                                                            │
│ /home/zeth/PycharmProjects/CellVGAE/example_data/h5py/_conv.pyx:95 in h5py._conv.generic_converter                                                                                         │
│                                                                                                                                                                                            │
│ [Errno 2] No such file or directory: '/home/zeth/PycharmProjects/CellVGAE/example_data/h5py/_conv.pyx'                                                                                     │
│                                                                                                                                                                                            │
│ /home/zeth/PycharmProjects/CellVGAE/example_data/h5py/_conv.pyx:249 in h5py._conv.conv_str2vlen                                                                                            │
│                                                                                                                                                                                            │
│ [Errno 2] No such file or directory: '/home/zeth/PycharmProjects/CellVGAE/example_data/h5py/_conv.pyx'                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Can't implicitly convert non-string objects to strings

The above exception was the direct cause of the following exception:

╭──────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                                                            │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_io/utils.py:209 in func_wrapper                                                                                     │
│                                                                                                                                                                                            │
│   206 │   @wraps(func)                                                                                                                                                                     │
│   207 │   def func_wrapper(elem, key, val, *args, **kwargs):                                                                                                                               │
│   208 │   │   try:                                                                                                                                                                         │
│ ❱ 209 │   │   │   return func(elem, key, val, *args, **kwargs)                                                                                                                             │
│   210 │   │   except Exception as e:                                                                                                                                                       │
│   211 │   │   │   parent = _get_parent(elem)                                                                                                                                               │
│   212 │   │   │   raise type(e)(                                                                                                                                                           │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_io/h5ad.py:263 in write_dataframe                                                                                   │
│                                                                                                                                                                                            │
│   260 │                                                                                                                                                                                    │
│   261 │   write_series(group, index_name, df.index, dataset_kwargs=dataset_kwargs)                                                                                                         │
│   262 │   for col_name, (_, series) in zip(col_names, df.items()):                                                                                                                         │
│ ❱ 263 │   │   write_series(group, col_name, series, dataset_kwargs=dataset_kwargs)                                                                                                         │
│   264                                                                                                                                                                                      │
│   265                                                                                                                                                                                      │
│   266 @report_write_key_on_error                                                                                                                                                           │
│                                                                                                                                                                                            │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_io/utils.py:212 in func_wrapper                                                                                     │
│                                                                                                                                                                                            │
│   209 │   │   │   return func(elem, key, val, *args, **kwargs)                                                                                                                             │
│   210 │   │   except Exception as e:                                                                                                                                                       │
│   211 │   │   │   parent = _get_parent(elem)                                                                                                                                               │
│ ❱ 212 │   │   │   raise type(e)(                                                                                                                                                           │
│   213 │   │   │   │   f"{e}\n\n"                                                                                                                                                           │
│   214 │   │   │   │   f"Above error raised while writing key {key!r} of {type(elem)}"                                                                                                      │
│   215 │   │   │   │   f" from {parent}."                                                                                                                                                   │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key 'gender' of <class 'h5py._hl.group.Group'> from /.

The above exception was the direct cause of the following exception:

╭──────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────────────────────────────╮
│ <stdin>:1 in <module>                                                                                                                                                                      │
│ /home/zeth/PycharmProjects/ehrapy/ehrapy/io/_write.py:61 in write                                                                                                                          │
│                                                                                                                                                                                            │
│   58 │   │   │   │   "Cannot write AnnData object containing non-numerical values to .h5ad                                                                                                 │
│      file. Please "                                                                                                                                                                        │
│   59 │   │   │   │   "encode your AnnData object before writing!"                                                                                                                          │
│   60 │   │   │   )                                                                                                                                                                         │
│ ❱ 61 │   │   adata.write(filename, compression=compression,                                                                                                                                │
│      compression_opts=compression_opts)                                                                                                                                                    │
│   62                                                                                                                                                                                       │
│   63                                                                                                                                                                                       │
│   64 def _get_filename_from_key(key, extension=None) -> Path:                                                                                                                              │
│                                                                                                                                                                                            │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_core/anndata.py:1912 in write_h5ad                                                                                  │
│                                                                                                                                                                                            │
│   1909 │   │   if filename is None:                                                                                                                                                        │
│   1910 │   │   │   filename = self.filename                                                                                                                                                │
│   1911 │   │                                                                                                                                                                               │
│ ❱ 1912 │   │   _write_h5ad(                                                                                                                                                                │
│   1913 │   │   │   Path(filename),                                                                                                                                                         │
│   1914 │   │   │   self,                                                                                                                                                                   │
│   1915 │   │   │   compression=compression,                                                                                                                                                │
│                                                                                                                                                                                            │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_io/h5ad.py:111 in write_h5ad                                                                                        │
│                                                                                                                                                                                            │
│   108 │   │   │   )                                                                                                                                                                        │
│   109 │   │   else:                                                                                                                                                                        │
│   110 │   │   │   write_attribute(f, "raw", adata.raw, dataset_kwargs=dataset_kwargs)                                                                                                      │
│ ❱ 111 │   │   write_attribute(f, "obs", adata.obs, dataset_kwargs=dataset_kwargs)                                                                                                          │
│   112 │   │   write_attribute(f, "var", adata.var, dataset_kwargs=dataset_kwargs)                                                                                                          │
│   113 │   │   write_attribute(f, "obsm", adata.obsm, dataset_kwargs=dataset_kwargs)                                                                                                        │
│   114 │   │   write_attribute(f, "varm", adata.varm, dataset_kwargs=dataset_kwargs)                                                                                                        │
│                                                                                                                                                                                            │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/functools.py:875 in wrapper                                                                                                                │
│                                                                                                                                                                                            │
│   872 │   │   │   raise TypeError(f'{funcname} requires at least '                                                                                                                         │
│   873 │   │   │   │   │   │   │   '1 positional argument')                                                                                                                                 │
│   874 │   │                                                                                                                                                                                │
│ ❱ 875 │   │   return dispatch(args[0].__class__)(*args, **kw)                                                                                                                              │
│   876 │                                                                                                                                                                                    │
│   877 │   funcname = getattr(func, '__name__', 'singledispatch function')                                                                                                                  │
│   878 │   registry[object] = func                                                                                                                                                          │
│                                                                                                                                                                                            │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_io/h5ad.py:130 in write_attribute_h5ad                                                                              │
│                                                                                                                                                                                            │
│   127 def write_attribute_h5ad(f: H5Group, key: str, value, *args, **kwargs):                                                                                                              │
│   128 │   if key in f:                                                                                                                                                                     │
│   129 │   │   del f[key]                                                                                                                                                                   │
│ ❱ 130 │   _write_method(type(value))(f, key, value, *args, **kwargs)                                                                                                                       │
│   131                                                                                                                                                                                      │
│   132                                                                                                                                                                                      │
│   133 def write_raw(f, key, value, dataset_kwargs=MappingProxyType({})):                                                                                                                   │
│                                                                                                                                                                                            │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_io/utils.py:212 in func_wrapper                                                                                     │
│                                                                                                                                                                                            │
│   209 │   │   │   return func(elem, key, val, *args, **kwargs)                                                                                                                             │
│   210 │   │   except Exception as e:                                                                                                                                                       │
│   211 │   │   │   parent = _get_parent(elem)                                                                                                                                               │
│ ❱ 212 │   │   │   raise type(e)(                                                                                                                                                           │
│   213 │   │   │   │   f"{e}\n\n"                                                                                                                                                           │
│   214 │   │   │   │   f"Above error raised while writing key {key!r} of {type(elem)}"                                                                                                      │
│   215 │   │   │   │   f" from {parent}."                                                                                                                                                   │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key 'gender' of <class 'h5py._hl.group.Group'> from /.

Above error raised while writing key 'obs' of <class 'h5py._hl.files.File'> from /.

```

**To Reproduce**

Steps to reproduce the behavior:

```
import ehrapy as ep

adata = ep.dt.diabetes_130(encoded=False, columns_obs_only=["age",
                                                            "age_mean",
                                                            "weight_mean",
                                                            "weight",
                                                            "patient_nbr",
                                                            "payer_code"
                                                            ])
adata=ep.pp.encode(adata,autodetect=True)
ep.pp.knn_impute(adata)
ep.io.write("diabetes_130.h5ad", adata)
```

I guess that the columns that only contain floats but are for some reason in object columns cause these issues?
```
>>> adata.obs["gender"]
encounter_id
2278392      0.0
149190       0.0
64410        0.0
500364       1.0
16680        1.0
            ... 
443847548    1.0
443847782    0.0
443854148    1.0
443857166    0.0
443867222    1.0
Name: gender, Length: 101766, dtype: object
```

**Comment by Imipenem** [comment]
@Zethson can u pls test this by not calling `write` but setting `cache=True` while reading?

**Comment by Zethson** [comment]
Sadly, we are not exposing cache=True to the dataloaders

https://ehrapy.readthedocs.io/en/development/usage/data/ehrapy.data.diabetes_130.html#ehrapy.data.diabetes_130

Should we? But in any case, something is wrong here because this has to work with and without caching. The full code to reproduce this is above and I'd appreciate it if you could take some time to look at this.

**Comment by Imipenem** [comment]
Just download and read it. This would tell if it works with the things implemented in cache or its something deeper.

**Comment by Zethson** [comment]
```
adata_test = ep.io.read("ehrapy_data/diabetes_130.csv", columns_obs_only=["age",
                                                            "age_mean",
                                                            "weight_mean",
                                                            "weight",
                                                            "patient_nbr",
                                                            "payer_code"
                                                            ], cache=True)
```
```

╭──────────────────────────── Traceback (most recent call last) ────────────────────────────╮
│                                                                                           │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_io/utils.py:209 in │
│ func_wrapper                                                                              │
│                                                                                           │
│   206 │   @wraps(func)                                                                    │
│   207 │   def func_wrapper(elem, key, val, *args, **kwargs):                              │
│   208 │   │   try:                                                                        │
│ ❱ 209 │   │   │   return func(elem, key, val, *args, **kwargs)                            │
│   210 │   │   except Exception as e:                                                      │
│   211 │   │   │   parent = _get_parent(elem)                                              │
│   212 │   │   │   raise type(e)(                                                          │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_io/h5ad.py:270 in  │
│ write_series                                                                              │
│                                                                                           │
│   267 def write_series(group, key, series, dataset_kwargs=MappingProxyType({})):          │
│   268 │   # group here is an h5py type, otherwise categoricals won’t write                │
│   269 │   if series.dtype == object:  # Assuming it’s string                              │
│ ❱ 270 │   │   group.create_dataset(                                                       │
│   271 │   │   │   key,                                                                    │
│   272 │   │   │   data=series.values,                                                     │
│   273 │   │   │   dtype=h5py.special_dtype(vlen=str),                                     │
│                                                                                           │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/h5py/_hl/group.py:149 in    │
│ create_dataset                                                                            │
│                                                                                           │
│   146 │   │   │   │   │   parent_path, name = name.rsplit(b'/', 1)                        │
│   147 │   │   │   │   │   group = self.require_group(parent_path)                         │
│   148 │   │   │                                                                           │
│ ❱ 149 │   │   │   dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)   │
│   150 │   │   │   dset = dataset.Dataset(dsid)                                            │
│   151 │   │   │   return dset                                                             │
│   152                                                                                     │
│                                                                                           │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/h5py/_hl/dataset.py:145 in  │
│ make_new_dset                                                                             │
│                                                                                           │
│    142 │   dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl)                     │
│    143 │                                                                                  │
│    144 │   if (data is not None) and (not isinstance(data, Empty)):                       │
│ ❱  145 │   │   dset_id.write(h5s.ALL, h5s.ALL, data)                                      │
│    146 │                                                                                  │
│    147 │   return dset_id                                                                 │
│    148                                                                                    │
│                                                                                           │
│ /home/zeth/PycharmProjects/ehrapy-tutorials/h5py/_objects.pyx:54 in                       │
│ h5py._objects.with_phil.wrapper                                                           │
│                                                                                           │
│ [Errno 2] No such file or directory:                                                      │
│ '/home/zeth/PycharmProjects/ehrapy-tutorials/h5py/_objects.pyx'                           │
│                                                                                           │
│ /home/zeth/PycharmProjects/ehrapy-tutorials/h5py/_objects.pyx:55 in                       │
│ h5py._objects.with_phil.wrapper                                                           │
│                                                                                           │
│ [Errno 2] No such file or directory:                                                      │
│ '/home/zeth/PycharmProjects/ehrapy-tutorials/h5py/_objects.pyx'                           │
│                                                                                           │
│ /home/zeth/PycharmProjects/ehrapy-tutorials/h5py/h5d.pyx:232 in h5py.h5d.DatasetID.write  │
│                                                                                           │
│ [Errno 2] No such file or directory:                                                      │
│ '/home/zeth/PycharmProjects/ehrapy-tutorials/h5py/h5d.pyx'                                │
│                                                                                           │
│ /home/zeth/PycharmProjects/ehrapy-tutorials/h5py/_proxy.pyx:145 in h5py._proxy.dset_rw    │
│                                                                                           │
│ [Errno 2] No such file or directory:                                                      │
│ '/home/zeth/PycharmProjects/ehrapy-tutorials/h5py/_proxy.pyx'                             │
│                                                                                           │
│ /home/zeth/PycharmProjects/ehrapy-tutorials/h5py/_conv.pyx:444 in h5py._conv.str2vlen     │
│                                                                                           │
│ [Errno 2] No such file or directory:                                                      │
│ '/home/zeth/PycharmProjects/ehrapy-tutorials/h5py/_conv.pyx'                              │
│                                                                                           │
│ /home/zeth/PycharmProjects/ehrapy-tutorials/h5py/_conv.pyx:95 in                          │
│ h5py._conv.generic_converter                                                              │
│                                                                                           │
│ [Errno 2] No such file or directory:                                                      │
│ '/home/zeth/PycharmProjects/ehrapy-tutorials/h5py/_conv.pyx'                              │
│                                                                                           │
│ /home/zeth/PycharmProjects/ehrapy-tutorials/h5py/_conv.pyx:249 in                         │
│ h5py._conv.conv_str2vlen                                                                  │
│                                                                                           │
│ [Errno 2] No such file or directory:                                                      │
│ '/home/zeth/PycharmProjects/ehrapy-tutorials/h5py/_conv.pyx'                              │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Can't implicitly convert non-string objects to strings

The above exception was the direct cause of the following exception:

╭──────────────────────────── Traceback (most recent call last) ────────────────────────────╮
│                                                                                           │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_io/utils.py:209 in │
│ func_wrapper                                                                              │
│                                                                                           │
│   206 │   @wraps(func)                                                                    │
│   207 │   def func_wrapper(elem, key, val, *args, **kwargs):                              │
│   208 │   │   try:                                                                        │
│ ❱ 209 │   │   │   return func(elem, key, val, *args, **kwargs)                            │
│   210 │   │   except Exception as e:                                                      │
│   211 │   │   │   parent = _get_parent(elem)                                              │
│   212 │   │   │   raise type(e)(                                                          │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_io/h5ad.py:263 in  │
│ write_dataframe                                                                           │
│                                                                                           │
│   260 │                                                                                   │
│   261 │   write_series(group, index_name, df.index, dataset_kwargs=dataset_kwargs)        │
│   262 │   for col_name, (_, series) in zip(col_names, df.items()):                        │
│ ❱ 263 │   │   write_series(group, col_name, series, dataset_kwargs=dataset_kwargs)        │
│   264                                                                                     │
│   265                                                                                     │
│   266 @report_write_key_on_error                                                          │
│                                                                                           │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_io/utils.py:212 in │
│ func_wrapper                                                                              │
│                                                                                           │
│   209 │   │   │   return func(elem, key, val, *args, **kwargs)                            │
│   210 │   │   except Exception as e:                                                      │
│   211 │   │   │   parent = _get_parent(elem)                                              │
│ ❱ 212 │   │   │   raise type(e)(                                                          │
│   213 │   │   │   │   f"{e}\n\n"                                                          │
│   214 │   │   │   │   f"Above error raised while writing key {key!r} of {type(elem)}"     │
│   215 │   │   │   │   f" from {parent}."                                                  │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key 'gender' of <class 'h5py._hl.group.Group'> from /.

The above exception was the direct cause of the following exception:

╭──────────────────────────── Traceback (most recent call last) ────────────────────────────╮
│                                                                                           │
│ /tmp/ipykernel_170440/4198267726.py:1 in <cell line: 1>                                   │
│                                                                                           │
│ [Errno 2] No such file or directory: '/tmp/ipykernel_170440/4198267726.py'                │
│ /home/zeth/PycharmProjects/ehrapy/ehrapy/io/_read.py:102 in read                          │
│                                                                                           │
│    99 │   │   shutil.move(output_file_or_dir, moved_path)  # type: ignore                 │
│   100 │   │   file = moved_path                                                           │
│   101 │                                                                                   │
│ ❱ 102 │   raw_object = _read(                                                             │
│   103 │   │   filename=file,                                                              │
│   104 │   │   extension=extension,                                                        │
│   105 │   │   delimiter=delimiter,                                                        │
│                                                                                           │
│ /home/zeth/PycharmProjects/ehrapy/ehrapy/io/_read.py:173 in _read                         │
│                                                                                           │
│   170 │   │   │   if cache:                                                               │
│   171 │   │   │   │   if not path_cache.parent.is_dir():                                  │
│   172 │   │   │   │   │   path_cache.parent.mkdir(parents=True)                           │
│ ❱ 173 │   │   │   │   return _write_cache(raw_anndata, path_cache, columns_obs_only)  # t │
│       ignore                                                                              │
│   174 │   │                                                                               │
│   175 │   │   elif extension == "pdf":                                                    │
│   176 │   │   │   raw_anndata, columns_obs_only = read_pdf(                               │
│                                                                                           │
│ /home/zeth/PycharmProjects/ehrapy/ehrapy/io/_read.py:499 in _write_cache                  │
│                                                                                           │
│   496 │   cached_adata = encode(data=raw_anndata, autodetect=True)                        │
│   497 │   # temporary key that stores all column names that are obs only for this AnnData │
│       object                                                                              │
│   498 │   cached_adata.uns["cache_temp_obs_only"] = columns_obs_only                      │
│ ❱ 499 │   cached_adata.write(path_cache)                                                  │
│   500 │   cached_adata.X = cached_adata.X.astype("object")                                │
│   501 │   cached_adata = _decode_cached_adata(cached_adata, columns_obs_only)             │
│   502 │   return cached_adata                                                             │
│                                                                                           │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_core/anndata.py:19 │
│ 12 in write_h5ad                                                                          │
│                                                                                           │
│   1909 │   │   if filename is None:                                                       │
│   1910 │   │   │   filename = self.filename                                               │
│   1911 │   │                                                                              │
│ ❱ 1912 │   │   _write_h5ad(                                                               │
│   1913 │   │   │   Path(filename),                                                        │
│   1914 │   │   │   self,                                                                  │
│   1915 │   │   │   compression=compression,                                               │
│                                                                                           │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_io/h5ad.py:111 in  │
│ write_h5ad                                                                                │
│                                                                                           │
│   108 │   │   │   )                                                                       │
│   109 │   │   else:                                                                       │
│   110 │   │   │   write_attribute(f, "raw", adata.raw, dataset_kwargs=dataset_kwargs)     │
│ ❱ 111 │   │   write_attribute(f, "obs", adata.obs, dataset_kwargs=dataset_kwargs)         │
│   112 │   │   write_attribute(f, "var", adata.var, dataset_kwargs=dataset_kwargs)         │
│   113 │   │   write_attribute(f, "obsm", adata.obsm, dataset_kwargs=dataset_kwargs)       │
│   114 │   │   write_attribute(f, "varm", adata.varm, dataset_kwargs=dataset_kwargs)       │
│                                                                                           │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/functools.py:875 in wrapper               │
│                                                                                           │
│   872 │   │   │   raise TypeError(f'{funcname} requires at least '                        │
│   873 │   │   │   │   │   │   │   '1 positional argument')                                │
│   874 │   │                                                                               │
│ ❱ 875 │   │   return dispatch(args[0].__class__)(*args, **kw)                             │
│   876 │                                                                                   │
│   877 │   funcname = getattr(func, '__name__', 'singledispatch function')                 │
│   878 │   registry[object] = func                                                         │
│                                                                                           │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_io/h5ad.py:130 in  │
│ write_attribute_h5ad                                                                      │
│                                                                                           │
│   127 def write_attribute_h5ad(f: H5Group, key: str, value, *args, **kwargs):             │
│   128 │   if key in f:                                                                    │
│   129 │   │   del f[key]                                                                  │
│ ❱ 130 │   _write_method(type(value))(f, key, value, *args, **kwargs)                      │
│   131                                                                                     │
│   132                                                                                     │
│   133 def write_raw(f, key, value, dataset_kwargs=MappingProxyType({})):                  │
│                                                                                           │
│ /home/zeth/miniconda3/envs/ehrapy/lib/python3.8/site-packages/anndata/_io/utils.py:212 in │
│ func_wrapper                                                                              │
│                                                                                           │
│   209 │   │   │   return func(elem, key, val, *args, **kwargs)                            │
│   210 │   │   except Exception as e:                                                      │
│   211 │   │   │   parent = _get_parent(elem)                                              │
│ ❱ 212 │   │   │   raise type(e)(                                                          │
│   213 │   │   │   │   f"{e}\n\n"                                                          │
│   214 │   │   │   │   f"Above error raised while writing key {key!r} of {type(elem)}"     │
│   215 │   │   │   │   f" from {parent}."                                                  │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Can't implicitly convert non-string objects to strings

Above error raised while writing key 'gender' of <class 'h5py._hl.group.Group'> from /.

Above error raised while writing key 'obs' of <class 'h5py._hl.files.File'> from /.


```
