### ISSUE TITLE
Misleading number of nan values for feature columns with missing values after their encoding 

### ISSUE THREAD

**Issue by HorlavaNastassya** [theislab/ehrapy#363]
**Describe the bug**

When using function 'qc_metrics', number of missing values is calculated for X. If before that adata object was encoded, and columns that were encoded had "nan" values, this "nan" values are then stored as a separate category (e.g. one hot encoded). When sum of missing values is then calculated, "nan" values of these encoded columns are excluded from the sum as they are not represented as "nan" anymore. 

**To Reproduce**

A toy example: 

<img width="729" alt="image" src="https://user-images.githubusercontent.com/22348380/160417173-ff73be8c-550b-473b-8a0b-7a3ea0557363.png">

**Expected behavior**

Function "qc_metrics" should probably check original values of the vars that were encoded rather than encoded ones when calculating number of missing values. 

**System [please complete the following information]:**

-   OS: e.g. macOS Big Sur
-   Language Version: Python 3.8
-   Virtual environment: Conda

**Additional context**

**Comment by Zethson** [comment]
Interesting. Didn't think of this.
Thank you!

**Comment by Zethson** [comment]
@Imipenem could you have a look at this and suggest a solution? @HorlavaNastassya proposed to fix this herself (though it is "our" fault)

**Comment by Zethson** [comment]
> IMO easiest solution would be what @HorlavaNastassya already wrote: Just use the original, unencoded values for qc_metrics if the AnnData object has already been encoded.

She said though that they weren't stored in "original" IIRC anymore?

**Comment by Imipenem** [comment]
Those are categorical columns. So the original layer changed of course.

**Comment by Zethson** [comment]
> Those are categorical columns. So the original layer changed. But the originals in uns should not?

Ahh, yeah I forgot about those. So the function should use the "originals" values in `.uns` and not the layer "originals", right? This is where my implementation goes wrong.

**Comment by xinyuejohn** [comment]
The following code will cause the error:
TypeError! Setting quality control metrics to nan. Did you encode your data?
```
adata = ep.dt.mimic_2(encoded=True)

_ = ep.pp.qc_metrics(adata)
ep.pl.qc_metrics(adata)
```
