### ISSUE TITLE
Harmonize miss_forest and mice_forest imputation function names

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#370]
Currently one has an underscore and the other does not.

**Comment by xinyuejohn** [comment]
I think in data_imputation.py, it is called miceforest_impute and miss_forest_impute.

**Comment by Zethson** [comment]
Yeah. I was thinking that they should be called.


`mice_forest_impute and miss_forest_impute`

miceforest_impute and missforest_impute

Likely the former. Don't worry :)
