### ISSUE TITLE
Plot coloring by boolean variables

### ISSUE THREAD

**Issue by xinyuejohn** [theislab/ehrapy#373]
**Describe the bug**

For plot function (ep.pl.pca, ep.pl.umap and so on):
When plot by coloring (color=some_variables), if these coloring variables are categorical variables with only 2 categories, we need to use "ehrapycat_" + variable_name instead of using variable_name directly, or there will be a TypeError: 
```
TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` 
operator or the logical_not function instead.
```

**To Reproduce**

Case 1:
```
import ehrapy as ep
adata = ep.dt.parkinsons(encoded=True, columns_obs_only=["name"])
ep.pp.norm_scale(adata)
ep.pp.neighbors(adata)
ep.tl.umap(adata)

# variable "status" has two categories, the following line will raise KeyError:
ep.pl.umap(adata, color=["status"], ncols=1, wspace=0.75)

# The following line can run
#ep.pl.umap(adata, color=["ehrapycat_status"], ncols=1, wspace=0.75)

```
Case 2:

```
import ehrapy as ep
adata = ep.dt.parkinsons(encoded=True, columns_obs_only=["name"])
ep.pp.norm_scale(adata)
ep.pp.neighbors(adata)
ep.pp.pca(adata)

# variable "status" has two categories, the following line will raise KeyError:
ep.pl.pca(adata, color=["status"])

# The following line can run
ep.pl.pca(adata, color=["ehrapycat_status"])

```

**Expected behavior**

**System [please complete the following information]:**

-   OS: [MacOS 12.2.1]
-   Language Version: [e.g. Python 3.8]
-   Versions: anndata==0.8.0 ehrapy==0.2.0
**Additional context**

**Comment by Imipenem** [comment]
Thats weird; I just had this situation in #367 (the column had `True/False and nan` values and was in `.obs`) and I did not ran into any issue. I used `umap` for my purposes there.

**Comment by Zethson** [comment]
@namsaraeva think that it would be best if we try to tackle this in scanpy directly and submit a PR to scanpy -> https://github.com/scverse/scanpy/issues/1646
