### ISSUE TITLE
Hide temporary encoding progress bar when writing to .h5ad files

### ISSUE THREAD

**Issue by Imipenem** [theislab/ehrapy#395]
**Is your feature request related to a problem? Please describe.**

Currently:
![image](https://user-images.githubusercontent.com/31141763/178339921-b5d63d07-3fd2-4eee-bbb4-2ebaf3ac44ec.png)

**Describe the solution you would like**

Guess the "feedback" via the progress bar could confuse users and does not add any informations, since the encoding just happens for internal reasons; users should never actually see it. Guess we should simply hide the progress bar.

**Comment by Zethson** [comment]
I'm not sure. The advantage is that for large datasets where it takes a long time it does actually show what's happening.

**Comment by Imipenem** [comment]
Hmm true, but IMO we need to add a better description here (or drop a note in the docs, can't find anything about it in our docs). Like this, it's a bit confusing what's going on here.

**Comment by Zethson** [comment]
Just needs another print statement ahead of it IMO. "Temporarily encoding to allow saving" (badly paraphrased)

**Comment by Imipenem** [comment]
Y, that's what I was talking about.
