### ISSUE TITLE
Provide `add_to_obs` function.

### ISSUE THREAD

**Issue by Imipenem** [theislab/ehrapy#396]
**Is your feature request related to a problem? Please describe.**

While working with the PICU data, I noticed it would be useful to not only be able to `move_to_obs` but also `add_to_obs`. The values should be copied to obs (and therefore kept in X) instead of moved completely.

**Describe the solution you would like**

This should be a parameter of the existing `move_to_obs` function and not a new function. Ensure that we add tests.

**Comment by Zethson** [comment]
Should this be a parameter of move_to_obs instead of a new function?
