### ISSUE TITLE
Offset negative values automatically

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#402]
When attempting to log normalize data with negative values, we currently run into errors because the log of negative numbers is not defined.

I see two options:

1. Add "offset_negative_values" function which pushes all of these to positive numbers with the lowest, most negative number becoming 0.
2. Using 1. but also adding a parameter to log_norm to do this automatically for columns with negative values

Thoughts @Imipenem ?

**Comment by Imipenem** [comment]
What about providing both options? 
I would like having this as a separate utility, as I can see this being used in other ways as well. 

And providing option 2 would be very convenient from a users perspective.

**Comment by Imipenem** [comment]
As an addition: It seems like `ep.pp.log_norm` would run without raising any errors, even when there are negative values in the data. We should warn about this with a short notice (even when this issue got implemented); cost me like half an hour to figure out why `ep.pp.neighbors` failed to run after `log_norm`, even if `log_norm` ran without any errors. Seems like it just replaced log(neg_val) with `nans` ...

**Comment by Imipenem** [comment]
Note: Ideally, this should be calculated after the `originals` layer got created, so we don't loose the real values, which are important for further analysis.

**Comment by Zethson** [comment]
@Imipenem we're pushing ALL values then, right? Not just the negative ones.

-> matrix of `[[-1, -5, 2], [6, 2, 1]]` would become `[[4, 0, 7], [11, 7, 6]]`
