### ISSUE TITLE
mimic 2 fate notebook sometimes randomly times out

### ISSUE THREAD

**Issue by namsaraeva** [theislab/ehrapy#421]
**Describe the bug**

I noticed that the notebook checks (the **Run** step) take a very long time after pushing changes to any branch. Moreover, they fail after running for around 5-6h. 

From what I've seen, the `mimic_2_fate.ipynb` notebook takes the longest and fails almost every time. But there might be other issues with other notebooks as well. 

**To Reproduce**

1. Commit a change
2. Push a change
3. See that it indeed takes forever...

**Expected behavior**

From older logs I see that the notebook checks should take around 12-15 minutes on average.

**Comment by Zethson** [comment]
So it runs through flawlessly locally...
Maybe an environment issue?

**Comment by Zethson** [comment]
This one even runs through in 15 minutes ??!?
https://github.com/theislab/ehrapy/actions/runs/3516528889/jobs/5893205650

**Comment by Zethson** [comment]
Just closing because IDK what to do. I'll reopen if I find out more.
