### ISSUE TITLE
ep.pp.qc_lab_measurements cannot deal with some measurements

### ISSUE THREAD

**Issue by xinyuejohn** [theislab/ehrapy#447]
**Describe the bug**

**To Reproduce**

```
import pandas as pd
import ehrapy as ep
import numpy as np
data = pd.DataFrame(np.array([[100, 98], [162, 107]]), columns=['oxygen saturation', 'glucose'], index=[0, 1])
adata = ep.ad.df_to_anndata(data)

# This will cause ValueError (ValueError: could not convert string to float: '0.7 0.3')
ep.pp.qc_lab_measurements(adata, measurements=['oxygen saturation'])

```

**System [please complete the following information]:**

-   OS: e.g. [MacOS 13.1]
-   Language Version: [Python 3.8]
-   Virtual environment: [Conda]

**Additional context**

1) In the above example, measurements=['oxygen saturation'], and the final matched array has 2 rows:

	<img width="234" alt="Screenshot 2023-04-11 at 22 09 25" src="https://user-images.githubusercontent.com/88339105/231277212-391f3b04-2444-441e-aa59-9211120b62a3.png">

2) The final matched array will be transformed to a string:
`check_str: str = np.array2string(check)`
	Then the array will transformed to "0.2-0.7 0.3-0.9"
3) Then the string will be split by:
	```
	min_value = float(check_str.split("-")[0])
    max_value = float(check_str.split("-")[1]) 
	```
	It will case error.

**Suggest solution**
	
Make sure the final matched array has only one row by aggregating several rows in some way. (By warning the user input more information, e.g. sex_col, age_col, ethnicity_col or just simply averaging several rows.

**Comment by Zethson** [comment]
Thank you! Could you please fix it quickly? Thanks

**Comment by Zethson** [comment]
Think that @xinyuejohn mentioned at some point that this is a bit more broken and requires more fixes? Would be awesome if @xinyuejohn and @namsaraeva you could quickly connect on mattermost/IRL and discuss this so that @namsaraeva can fix this?

@namsaraeva this doesn't have a high priority, but should get fixed after you're more free and have some more time.

**Comment by xinyuejohn** [comment]
I will talk to @namsaraeva after I finish Reproduce Eulenberg.

**Comment by namsaraeva** [comment]
@Zethson @xinyuejohn I am working on it

**Comment by xinyuejohn** [comment]
In the documentation of `ehrapy.preprocessing.qc_lab_measurement()`, one limitation is "By default if no gender is provided and no unisex values are available, we use the male reference ranges.".

However, the above example `ep.pp.qc_lab_measurements(adata, measurements=['oxygen saturation'])` doesn't follow this way, which use male reference ranges. The results contain male and female ranges:

<img width="234" alt="Screenshot 2023-04-11 at 22 09 25" src="https://user-images.githubusercontent.com/88339105/231277212-391f3b04-2444-441e-aa59-9211120b62a3.png">

I suggest starting fixing this bug first and see what we can further improve this function.

One more thing: I found the default used reference table is not complete, compared to its original version from https://accessmedicine.mhmedical.com/content.aspx?bookid=1069&sectionid=60775149 .

**Comment by Zethson** [comment]
@namsaraeva and me discussed the "several options are available issue". We should error out when this is the case.

Please add any missing meausrements from the reference table. Not sure what happened here.
