### ISSUE TITLE
Data imputation

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#45]
Contrary to count data we can actually infer statistics from the data and impute it. Very important here again to be able to selectively apply these imputations to specific columns.

- [ ] Replacing with an explicit value
- [ ] KNN imputation
- [ ] Mean imputation
- [ ] z-score imputation
- [ ] fully conditional specification multiple imputation https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4945131/
- [ ] multiple imputation with chained equations using classification and regression trees (MICE)  https://towardsdatascience.com/multiple-imputation-with-random-forests-in-python-dec83c0ac55b

**Comment by Imipenem** [comment]
https://scikit-learn.org/stable/auto_examples/impute/plot_missing_values.html#sphx-glr-auto-examples-impute-plot-missing-values-py

Might be a good read here.

**Comment by Imipenem** [comment]
@Zethson; I can find a lot of published papers and articles online that state using mean imputation is a very bad way to impute data and should be avoided (especially because relationship between variables in a dataset might be lost). Since we have some good alternatives: What do you think of not exposing this one via our ehrapy API?

**Comment by Zethson** [comment]
> @Zethson; I can find a lot of published papers and articles online that state using mean imputation is a very bad way to impute data and should be avoided (especially because relationship between variables in a dataset might be lost). Since we have some good alternatives: What do you think of not exposing this one via our ehrapy API?

I'd offer it anyways because it is trivial to implement. I guess by the time that we know which methods actually suit our data we can still trivially disable it.

**Comment by Imipenem** [comment]
Fair enough. I will anyways restrict `mean` and `median` imputation to numerical data, since applying those to text data for example will just render a meaningless value that can not be mapped to any meaningful value.
