### ISSUE TITLE
Add command to display available encoding modes for categorical values

### ISSUE THREAD

**Issue by Imipenem** [theislab/ehrapy#55]
**Is your feature request related to a problem? Please describe.**

Currently, there is no simple CLI command/API utility function to get all available encoding modes for categorical values. 

Users either have to read the docs or look at the source code. 

**Describe the solution you would like**

Let's add a simple CLI command/API function to display all available encoding modes (with some info for each one)

**Comment by Zethson** [comment]
We will not use the CLI for a long time because we expect our users to interact with it via Jupyter Notebooks. IMO this should all be autogenerated from doc strings via Sphinx.
