### ISSUE TITLE
Trouble encoding synthea dataset

### ISSUE THREAD

**Issue by namsaraeva** [theislab/ehrapy#570]
Calling `adata = ep.dt.synthea_1k_sample(encoded=True)` throws `ValueError: setting an array element with a sequence` .

Full error in the next comment. 

Python 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]
Linux-5.14.21-150400.24.41-default-x86_64-with-glibc2.31
Session information updated at 2023-07-28 15:13

**Comment by Zethson** [comment]
We'll remove FHIR support
