### ISSUE TITLE
RuntimeError importing synthea dataset locally

### ISSUE THREAD

**Issue by namsaraeva** [theislab/ehrapy#571]
### Report

Running `adata = ep.dt.synthea_1k_sample(encoded=True)` or `adata = ep.dt.synthea_1k_sample(encoded=False)` gives 

RuntimeError: 
An attempt has been made to start a new process before the current process has finished its bootstrapping phase.
This probably means that you are not using fork to start your child processes and you have forgotten to use the proper idiom in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

System: macOS Ventura 13.2.1 (22D68)

**Comment by namsaraeva** [comment]
Full error:
[synthea.txt](https://github.com/theislab/ehrapy/files/12194967/synthea.txt)

**Comment by Zethson** [comment]
This issue only occurs on MacOS. We're not sure why

**Comment by Zethson** [comment]
Remove the whole data loader
