### ISSUE TITLE
Specifying encoding vs autodetect True result in different outcomes

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#576]
### Question

```
adata = ep.dt.mimic_2(encoded=True)
adata.var
```

-> 46 vars

> ehrapycat_day_icu_intime
ehrapycat_service_unit

```
adata = ep.dt.mimic_2(encoded=False)
adata = ep.pp.encode(adata, encodings={"one_hot_encoding": ["service_unit", "day_icu_intime"]})
adata.var
```

-> results in 54 vars

> ehrapycat_service_unit_FICU
ehrapycat_service_unit_MICU
ehrapycat_service_unit_SICU
ehrapycat_day_icu_intime_Friday
ehrapycat_day_icu_intime_Monday
ehrapycat_day_icu_intime_Saturday
ehrapycat_day_icu_intime_Sunday
ehrapycat_day_icu_intime_Thursday
ehrapycat_day_icu_intime_Tuesday
ehrapycat_day_icu_intime_Wednesday

Is this intended?

**Comment by Imipenem** [comment]
This is generally not intended. 

Fix though is rather simple. 
When neither autodetect nor encodings is provided, currently the default encoding is label encoding. 

So we shoulde just change that to one hot encoding.

**Comment by Zethson** [comment]
Ohhh I thought we had already done that!

Aug 8, 2023 6:41:58 PM Philipp Ehmele ***@***.***>:
