### ISSUE TITLE
Test scalability of reading datasets

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#59]
We want to compare our custom parsing of the csvs with just reading the data into a Pandas DF.

- [x] 100x MIMIC 2 to make it bigger
- [x] write method to transform PD DF into AnnData
- [x] timeit both and compare

**Comment by Imipenem** [comment]
@Zethson 
first findings: 
Our read function will read a .csv file with about 200k lines in about 5,5 sec (with a ready to use AnnData object)
Pandas _read_csv()_ gives us a dataframe in about 0.5 seconds
Will update this with a function __df_to_ann_data__ to check, if this is a real speedup like it seems to be

**Comment by Zethson** [comment]
Tests were performed and we are perfectly fine with Pandas.
