### ISSUE TITLE
Cannot access medcat model

### ISSUE THREAD

**Issue by yorkofyou** [theislab/ehrapy#591]
### Report

https://medcat.rosalind.kcl.ac.uk/media/medmen_wstatus_2021_oct.zip

**Comment by Zethson** [comment]
Dear @yorkofyou 

I'll look into this soon. I may also redesign the medcat support completely. Please remain patient.

**Comment by eroell** [comment]
Thanks for raising this (and confirming my struggle that this indeed is not working)
It appears the link has been updated to this one: we will fix this link in the future tutorial.
https://cogstack-medcat-example-models.s3.eu-west-2.amazonaws.com/medcat-example-models/medmen_wstatus_2021_oct.zip
