### ISSUE TITLE
rank feature groups should also be possible to be applied to obs

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#593]
### Description of feature

It has been requested by multiple people that rank feature group should somehow also work for obs.

- [ ] Investigate whether and how it's possible to do so. As few API changes as possible
- [ ] Implement it
- [ ] Add tests

**Comment by eroell** [comment]
Regarding: Investigation whether and how it's possible to do so:

- Were the requests interested in using _only_ columns of `.obs`, or rather mix columns of `.obs` and `.layer`?
    - Or is it unspecified?
- Do you happen to know whether there were particular reasons to not use `move_to_x`?
    - I can imagine the reason "I dont want to modify my object and maybe make mistakes doing that, but just quickly add some `.obs `columns in this ranking, too"
    - Atm my thoughts circle around using this under the hood as the main "engine" introduced in this update
- From a user perspective, I suppose they were looking for an argument named e.g. `obs_cols_to_rank`, which would take a list of `.obs` keys as argument. Agree or think I'm off here?
- `filter_rank_genes_groups` might be the particular downstream task with most additional design choices to be made. No question here yet, leaning towards being conservative about removing things from `.obs`

**Comment by Zethson** [comment]
> filter_rank_genes_groups might be the particular downstream task with most additional design choices to be made. No question here yet, leaning towards being conservative about removing things from .obs

I think that most people are just interested in a `rank_feature_groups` plot.

> Were the requests interested in using only columns of .obs, or rather mix columns of .obs and .layer?

I could also foresee a mix of both being very useful. This would however make the implementation more complex. I think that we can do this in a two step process starting with only obs
