### ISSUE TITLE
Imputation fails for objects with empty columns

### ISSUE THREAD

**Issue by namsaraeva** [theislab/ehrapy#611]
### Description of feature

While trying to analyze the neonates data, `knn_impute()` (and `mice_forest_imputation()` probably, too) failed with this error:

![grafik](https://github.com/theislab/ehrapy/assets/99650244/32572854-81ce-4c7a-9268-292bb40697ad)

After digging a little bit deeper, @Zethson noticed that columns that are empty are the reason for wrong shapes. You can't impute something that has no data anyway, so we need to return a clearer error statement.

**Comment by Zethson** [comment]
I'll take care of this one

**Comment by namsaraeva** [comment]
This is probably connected to the issue as well: 

![grafik](https://github.com/theislab/ehrapy/assets/99650244/06fd65db-5073-47a3-a661-130c7ded0ac0)

**Comment by Zethson** [comment]
Waiting for more details, but maybe something along the lines of

```
import numpy as np
import dask.array as da
from scipy.sparse import issparse

def is_empty_column(array):
    def is_empty(element):
        return (element == '' or element is None) if isinstance(element, (str, type(None))) else np.isnan(element)

    if issparse(array):
        return np.array([array.getcol(i).nnz == 0 for i in range(array.shape[1])])
    elif isinstance(array, da.Array):
        return da.apply_along_axis(lambda column: np.all([is_empty(element) for element in column]), 0, array)
    else:
        return np.all(np.vectorize(is_empty)(array), axis=0)

# NumPy array with dtype object or number
numpy_array_mixed = np.array([[1, 0, 3], [np.nan, '', ''], [4, 0, '']])
result_numpy_mixed = is_empty_column(numpy_array_mixed)

# Dask array with dtype object or number
dask_array_mixed = da.from_array([[1, 0, 3], [np.nan, '', ''], [4, 0, '']], chunks=(2, 2))
result_dask_mixed = is_empty_column(dask_array_mixed)
```
