### ISSUE TITLE
Make scikit-learn-intelex an optional dependency

### ISSUE THREAD

**Issue by Lilly-May** [theislab/ehrapy#617]
### Report

In order to be able to install ehrapy on machines with MacOS and ARM architecture (M-chips), we need to make `scikit-learn-intelex` an optional dependency.
I had a quick look where the module `sklearnex` is used and it seems that one always checks if the module is importable anyways before actually using it. Hence, making it an optional dependency should not cause any problems.

**Comment by Zethson** [comment]
Done.
