### ISSUE TITLE
Encoding information should be stored in var if possible

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#649]
### Description of feature

Currently doing stuff like

```
encoded_ann_data.uns["var_to_encoding"] = {categorical: encodings for categorical in categoricals_names}
encoded_ann_data.uns["encoding_to_var"] = {encodings: categoricals_names}
```

**Comment by Lilly-May** [comment]
I've merged this issue with the related issues #662 and #637 into the new issue #701 for a better overview. Therefore, I'll close this issue here.
