### ISSUE TITLE
Single implementation of column type autodetection

### ISSUE THREAD

**Issue by eroell** [theislab/ehrapy#662]
### Description of feature

Column type autodetection (e.g. whether numeric or categorical) is required at different stages of ehrapy

E.g. the `autodetect` option of `encoding` [here](https://github.com/theislab/ehrapy/blob/82be78ebbc986c940ee0801f5bbda39c33eaf6ff/ehrapy/preprocessing/_encoding.py#L84) relies on the `adata.var[EHRAPY_TYPE_KEY]` tag.

This is set when
- reading a dataframe [here](https://github.com/theislab/ehrapy/blob/82be78ebbc986c940ee0801f5bbda39c33eaf6ff/ehrapy/anndata/anndata_ext.py#L91)
- moving something from obs to X [here](https://github.com/theislab/ehrapy/blob/82be78ebbc986c940ee0801f5bbda39c33eaf6ff/ehrapy/anndata/anndata_ext.py#L602).

We might want to harmonize that? It is the `df.select_dtypes("number").columns` pattern pretty consistently it appears at a first glance, but seems to be scattered.

Other places where this occurs and should be harmonized:
- in the [CohortTracker](https://github.com/theislab/ehrapy/blob/4090f6fca1265bfc1431a79a66bfd79b89956611/ehrapy/tools/cohort_tracking/_cohort_tracker.py#L27) 

TODOs:

- [ ] collect where this type detection is done
- [ ] move it to a single implementation

**Comment by eroell** [comment]
[tableone](https://github.com/tompollard/tableone/blob/bfd6fbaa4ed3e9f59e1a75191c6296a2a80ccc64/tableone/tableone.py#L555) might have something fairly robust we could be interested in too

**Comment by Lilly-May** [comment]
I've merged this issue with the related issues #649 and #637 into the new issue #701 for a better overview. Therefore, I'll close this issue here.
