### ISSUE TITLE
Installation issue for cellrank in combination with ehrapy

### ISSUE THREAD

**Issue by mhaist94** [theislab/ehrapy#669]
### Report

Hi all, 
thanks for this wonderful tool. First tests with your provided datasets look really cool. However, so far I could not make CellRank work in combination with ehrapy (tried it on a Mac and Windows machine with either first installing ehrapy 0.7.0 and then Cellrank or the other way round). Basically, after installing CellRank the encoding function (ep.pp.encode) will shoot me an error. Any idea what might be the issue here (screenshot below)?
Thanks all!
Max

<img width="664" alt="image" src="https://github.com/theislab/ehrapy/assets/115837960/75024629-4d29-414b-b0af-ba9c216c42c8">
 

### Version information

anndata             0.10.6
ehrapy              0.7.0
matplotlib          3.7.1
pandas              2.2.1
seaborn             0.13.2
session_info        1.0.0
-----
PIL                 10.2.0
asttokens           NA
attr                23.2.0
autograd            NA
autograd_gamma      NA
backcall            0.2.0
bs4                 4.12.3
cachetools          5.3.3
category_encoders   2.6.3
causallearn         NA
certifi             2024.02.02
charset_normalizer  3.3.2
colorama            0.4.6
comm                0.2.2
cycler              0.12.1
cython_runtime      NA
dateutil            2.9.0
...
Python 3.9.0 (default, Nov 15 2020, 08:30:55) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.17763-SP0
-----
Session information updated at 2024-03-13 22:30

**Comment by Zethson** [comment]
Dear @mhaist94 

thank you very much for playing around with it! I'm sorry for the inconvenience.
Here's what's happening:
When you're installing cellrank, it also installs scvelo (https://github.com/theislab/scvelo) which until recently, had a pin of scikit-learn. However, what you actually need is the latest version of scikit-learn.

So to resolve it, you probably just need to force upgrade the sciki-learn version. If you're still running into issues please come back and I'll lay out an explicit chain of commands to 100% get it resolved.

**Comment by Zethson** [comment]
I was also just told that scvelo will make a release this weekend which should fix this properly
