### ISSUE TITLE
Add h5ad caching for custom parser

### ISSUE THREAD

**Issue by Imipenem** [theislab/ehrapy#68]
**Is your feature request related to a problem? Please describe.**

Currently, ehrapy only supports reading data from `.csv` and `.tsv` files. For this purpose, we are using `pd.read_csv()`. It proofed fast enough and even faster than the custom read function with caching. 
So we do not need caching (writing/reading to/from `.h5ad` file) for those file formats. 

**One major Issue with using cache for those file formats was the following:**
Writing to `.h5ad` files of AnnData objects with mixed datatypes (strings and numericals in X for example, as it is a common case for ehrapy -> datatype `object`) does not work with current `h5py` versions.  See https://github.com/theislab/anndata/issues/558 for example. 
Since we're getting a `pd.Dataframe` as an intermediate step (and need to cast it to `np.array` for X using `pd.to_numpy()`) casting all values to `U (Unicode strings)` datatype works for caching, but this returns an all string X, which is not what we want to work with (and it's also very slow). 

**Describe the solution you would like**

For built-in parsers (csv/tsv) we're not gonna use any caching. 
But this may be required for custom parsers of custom file formats, that are not supported yet.

**Additional context**

**Comment by Zethson** [comment]
We will read and write encoded h5ad files like Scanpy.
X arrays that contain strings will work as follows:
1. print warning that this is slow and should not be done
2. Cast X as string
3. Save h5ad
4. Read in h5ad -> cast to object datatype

**Comment by Zethson** [comment]
@Imipenem this is done, right?

**Comment by Imipenem** [comment]
Yes @Zethson
