### ISSUE TITLE
read only file systems and example data download

### ISSUE THREAD

**Issue by bio-la** [theislab/ehrapy#699]
### Report

adata = ep.dt.diabetes_130_raw(encoded=False)
[...]
OSError: [Errno 30] Read-only file system: '/ehrapy_data'

maybe add info how to prepare the project directory for download? 

### Version information

-----
anndata             0.10.7
ehrapy              0.7.0
matplotlib          3.8.4
pandas              2.2.2
seaborn             0.13.2
session_info        1.0.0
-----
PIL                 10.3.0
appnope             0.1.4
asttokens           NA
autograd            NA
autograd_gamma      NA
bs4                 4.12.3
cachetools          5.3.3
category_encoders   2.6.3
causallearn         NA
certifi             2024.02.02
charset_normalizer  3.3.2
comm                0.2.2
cvxopt              1.3.2
cycler              0.12.1
cython_runtime      NA
dateutil            2.9.0
db_dtypes           1.2.0
...
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:53:34) [Clang 16.0.6 ]
macOS-14.4.1-x86_64-i386-64bit
-----

**Comment by eroell** [comment]
Hm, the `ehrapy_data` directory should typically be generated with not just read permissions
The way to solve on unix would be to go to the ehrapy directory and there do `chmod +wx ehrapy_data`.

Not sure under what circumstances read-only permissions are set to this created directory
