### ISSUE TITLE
API docs overview function table does not align properly

### ISSUE THREAD

**Issue by Imipenem** [theislab/ehrapy#71]
**Describe the bug**

![image](https://user-images.githubusercontent.com/31141763/129482637-9ec0807b-d14b-455e-9e3b-3d5b82e44faf.png)

As can be seen from the image above, the functions definitions within the tables do not align correctly over all tables.
See #63 as well.

**To Reproduce**

1. Check API docs

**Expected behavior**

They should be aligned over all tables

**Comment by Zethson** [comment]
Only the CSS master @Imipenem can solve this riddle. 🤦

**Comment by Zethson** [comment]
Should no longer be an issue since we moved to a new template.
