### ISSUE TITLE
To automate or not to automate infer_feature_types?

### ISSUE THREAD

**Issue by Zethson** [theislab/ehrapy#720]
### Description of feature

I volunteered to model all cases where it works and doesn't work. Based on this, we want to make an informed decision whether we can just enable the automation.

Types of data:

1. **Random numbers**: Randomly generated numeric values.
   ```python
   data = [42, 17, 93, 58]
   ```

2. **Strings**: Typical strings representing non-numeric data.
   ```python
   data = ["apple", "banana", "cherry", "date"]
   ```

3. **One-Hot Encoded**: Binary vectors representing categories.
   ```python
   data = [[0, 1, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0]]
   ```

4. **Label Encoded**: Integer encoded categorical data.
   ```python
   data = [1, 2, 3, 1]
   ```

5. **1/0 in int but also floats**:
   ```python
   data = [1.0, 2.0, 1.0, 2.0]
   ```

6. **Dates of all kinds**:
   ```python
   data = [20200101, 20200102, 20200103]
   ```

7. **Booleans**:
   ```python
   data = [True, False, True, False]
   ```

8. **Data containing NaNs**:
   ```python
   data = [NaN, 1, NaN, 2]
   ```

9. **Mixed data (strings + numbers)**:
   ```python
   data = ["apple", 1, "banana", 2]
   ```

10. **Numeric like categorical codes**:
    ```python
    data = ["001", "002", "003", "004"]
    ```

11. **Single value arrays**:
    ```python
    data = ["5", "5", "5", "5"]
    ```

12. **Alpha numeric codes**:
    ```python
    data = ["A1", "A2", "B1", "B2"]
    ```

13. **Zip codes**:
    ```python
    data = [90210, 10001, 60614]
    ```

14. **Fractions**:
    ```python
    data = [0.25, 0.5, 0.75, 1.0]
    ```

15. **Phone numbers**:
    ```python
    data = ["2125551234", "2125555678", "2125559012"]
    ```

16. **Currency/money**:
    ```python
    data = ["$100", "€150", "£200"]
    ```

17. **Similar numeric categorical IDs** (e.g., product IDs or location codes):
    ```python
    data = [101, 102, 103, 104]
    ```

18. **scientific notation**
    ```python
    data = [1e3, 5e-2, 3.1e2]
    ```

**Comment by Lilly-May** [comment]
Here's what the most recent version of `ep.ad.infer_feature_types` would detect:

1. Random numbers: `[42, 17, 93, 58]` → NUMERICAL_TAG
2. Strings: `["apple", "banana", "cherry", "date"]` → CATEGORICAL_TAG
3. One-Hot Encoded: `[[0, 1, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0]]` → Throws error (Do you mean storing a list in each adata.X cell for that feature?)
4. Label Encoded: `[1, 2, 3, 1]` → CATEGORICAL_TAG
5. 1/0 in int but also floats: `[1.0, 2.0, 1.0, 2.0]` → CATEGORICAL_TAG
6. Dates: `[20200101, 20200102, 20200103]` → NUMERICAL_TAG (if stored as strings, it's detected as date)
7. Booleans: `[True, False, True, False]` → CATEGORICAL_TAG
8. Data containing NaNs: `[NaN, 1, NaN, 2]` → CATEGORICAL_TAG
9. Mixed data (strings + numbers): `["apple", 1, "banana", 2]` → CATEGORICAL_TAG
10. Numeric like categorical codes: `["001", "002", "003", "004"]` → CATEGORICAL_TAG
11. Single value arrays: `["5", "5", "5", "5"]` → NUMERICAL_TAG
12. Alpha numeric codes: `["A1", "A2", "B1", "B2"]` → CATEGORICAL_TAG
13. Zip codes: `[90210, 10001, 60614]` → NUMERICAL_TAG
14. Fractions: `[0.25, 0.5, 0.75, 1.0]` → NUMERICAL_TAG
15. Phone numbers: `["2125551234", "2125555678", "2125559012"]` → NUMERICAL_TAG
16. Currency/money: `["$100", "€150", "£200"]` → CATEGORICAL_TAG
17. Similar numeric categorical IDs (e.g., product IDs or location codes): `[101, 102, 103, 104]` → NUMERICAL_TAG
18. scientific notation: `[1e3, 5e-2, 3.1e2]` → NUMERICAL_TAG
19. Floats as String: `["23.5", "324", "4.5", "0.5"]` → NUMERICAL_TAG

**Comment by Lilly-May** [comment]
In general, dates are only detected if they are stored in `pd.datetime` format or as strings in any [ISO format](https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.isoparse).

**Comment by Zethson** [comment]
OK so we settled on automating it with a few warnings for edge cases. See the upcoming PR :)
