### ISSUE TITLE
Maintenance: `uv` causes readthedocs build to fail 

### ISSUE THREAD

**Issue by eroell** [theislab/ehrapy#766]
### Report

using `uv` for the readthedocs build seems to cause an error with rust, about 'cargo' not found.

The pip install works, while being slower.
Find out what the upstream cause is for that, and then move back to using the faster `uv` for the readthedocs build.
- [x] Disable `uv` #763 
- [ ] Figure out what makes the readthedocs build fail here
- [ ] Report or fix
- [ ] Re-enable `uv`

**Comment by Zethson** [comment]
Should try again with this setup:

https://github.com/scverse/pertpy/blob/main/.readthedocs.yml
