### ISSUE TITLE
Import error "cannot import name 'AnyRandom' from 'scanpy._utils'"

### ISSUE THREAD

**Issue by safoora174** [theislab/ehrapy#776]
### Question

I installed the latest version of ehrapy(MACos Ventura  Version 13.6.7). When I run it I get this error:
cannot import name 'AnyRandom' from 'scanpy._utils' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/scanpy/_utils/__init__.py)
This is the version of my environment:
Package                  Version
------------------------ -----------
accelerate               0.32.1
aiofiles                 22.1.0
aiohttp                  3.9.5
aiosignal                1.3.1
aiosqlite                0.18.0
anndata                  0.10.8
annotated-types          0.6.0
anyio                    3.6.2
appnope                  0.1.3
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
array_api_compat         1.7.1
arrow                    1.2.3
asttokens                2.2.1
attrs                    22.2.0
autograd                 1.6.2
autograd-gamma           0.5.0
Babel                    2.12.1
backcall                 0.2.0
beautifulsoup4           4.11.2
bionty-base              0.37.3
bleach                   6.0.0
blis                     0.7.11
blosc                    1.11.1
botocore                 1.34.141
cachetools               5.3.3
catalogue                2.0.10
category-encoders        2.6.3
causal-learn             0.1.3.8
certifi                  2022.12.7
cffi                     1.15.1
chardet                  5.2.0
charset-normalizer       3.1.0
clarabel                 0.7.1
click                    8.1.7
cloudpathlib             0.18.1
comm                     0.1.2
confection               0.1.5
contourpy                1.0.7
cvxopt                   1.3.2
cvxpy                    1.4.3
cycler                   0.11.0
cymem                    2.0.8
Cython                   3.0.10
dacite                   1.8.1
datasets                 2.20.0
db-dtypes                1.2.0
debugpy                  1.6.6
decorator                5.1.1
deep-translator          1.11.4
deepl                    1.18.0
defusedxml               0.7.1
dill                     0.3.8
distlib                  0.3.7
dowhy                    0.11.1
ecos                     2.0.13
editdistance             0.8.1
ehrapy                   0.6.0
et-xmlfile               1.1.0
executing                1.2.0
faiss-cpu                1.8.0.post1
fancyimpute              0.7.0
fastjsonschema           2.16.3
fastobo                  0.12.3
fhiry                    4.0.0
filelock                 3.13.1
fknni                    1.1.1
fonttools                4.39.2
formulaic                1.0.1
fqdn                     1.5.1
frozenlist               1.4.1
fsspec                   2024.5.0
future                   1.0.0
gensim                   4.3.2
google-api-core          2.19.1
google-auth              2.32.0
google-cloud-bigquery    3.25.0
google-cloud-core        2.4.1
google-crc32c            1.5.0
google-resumable-media   2.7.1
googleapis-common-protos 1.63.2
googledrivedownloader    0.4
graphviz                 0.20.3
greenlet                 2.0.2
grpcio                   1.64.1
grpcio-status            1.64.1
h5py                     3.11.0
htmlmin                  0.1.12
huggingface-hub          0.23.4
humanfriendly            10.0
idna                     3.4
igraph                   0.11.6
ImageHash                4.3.1
imbalanced-learn         0.12.2
iniconfig                2.0.0
interface-meta           1.3.0
ipykernel                6.21.3
ipython                  8.11.0
ipython-genutils         0.2.0
ipywidgets               8.0.4
isoduration              20.11.0
jedi                     0.18.2
Jinja2                   3.1.4
jmespath                 1.0.1
joblib                   1.2.0
json5                    0.9.11
jsonpickle               3.2.2
jsonpointer              2.3
jsonschema               4.17.3
jupyter                  1.0.0
jupyter_client           8.0.3
jupyter-console          6.6.3
jupyter_core             5.3.0
jupyter-events           0.6.3
jupyter_server           2.5.0
jupyter_server_fileid    0.8.0
jupyter_server_terminals 0.4.4
jupyter_server_ydoc      0.6.1
jupyter-ydoc             0.2.3
jupyterlab               3.6.1
jupyterlab-pygments      0.2.2
jupyterlab_server        2.20.0
jupyterlab-widgets       3.0.5
kiwisolver               1.4.4
knnimpute                0.1.0
lamin_utils              0.13.2
langcodes                3.4.0
language_data            1.2.0
legacy-api-wrap          1.4
leidenalg                0.10.2
lifelines                0.29.0
lightgbm                 4.3.0
llvmlite                 0.42.0
marisa-trie              1.2.0
markdown-it-py           3.0.0
MarkupSafe               2.1.2
matplotlib               3.7.1
matplotlib-inline        0.1.6
mdurl                    0.1.2
medcat                   1.12.0
miceforest               5.7.0
missingno                0.5.2
mistune                  2.0.5
mlxtend                  0.21.0
mpmath                   1.3.0
multidict                6.0.5
multimethod              1.11.2
multiprocess             0.70.16
murmurhash               1.0.10
natsort                  8.4.0
nbclassic                0.5.3
nbclient                 0.7.2
nbconvert                7.2.10
nbformat                 5.7.3
nest-asyncio             1.5.6
networkx                 3.2.1
nltk                     3.8.1
nose                     1.3.7
notebook                 6.5.3
notebook_shim            0.2.2
numba                    0.59.1
numpy                    1.25.2
openpyxl                 3.1.5
osqp                     0.6.5
packaging                23.0
pandas                   2.2.2
pandocfilters            1.5.0
parso                    0.8.3
patsy                    0.5.6
peft                     0.11.1
pexpect                  4.8.0
phik                     0.12.4
pickleshare              0.7.5
Pillow                   9.4.0
pip                      24.1.2
pipenv                   2023.11.14
platformdirs             3.11.0
pluggy                   1.5.0
preshed                  3.0.9
prodict                  0.8.18
prometheus-client        0.16.0
prompt-toolkit           3.0.38
pronto                   2.5.5
proto-plus               1.24.0
protobuf                 5.27.2
psutil                   5.9.4
psycopg2-binary          2.9.6
ptyprocess               0.7.0
pure-eval                0.2.2
pyampute                 0.0.3
pyarrow                  16.1.0
pyarrow-hotfix           0.6
pyasn1                   0.6.0
pyasn1_modules           0.4.0
pybind11                 2.12.0
pycparser                2.21
pydantic                 1.10.17
pydantic_core            2.18.2
pydot                    2.0.0
Pygments                 2.14.0
pynndescent              0.5.13
pyparsing                3.0.9
PyQt5                    5.15.10
PyQt5-Qt5                5.15.12
PyQt5-sip                12.13.0
PyQtWebEngine            5.15.6
PyQtWebEngine-Qt5        5.15.12
pyrsistent               0.19.3
pytest                   8.2.0
python-dateutil          2.8.2
python-json-logger       2.0.7
pytz                     2022.7.1
PyWavelets               1.6.0
PyYAML                   6.0
pyzmq                    25.0.1
qdldl                    0.1.7.post2
qtconsole                5.4.1
QtPy                     2.3.0
rapidfuzz                3.9.4
regex                    2023.10.3
requests                 2.32.3
rfc3339-validator        0.1.4
rfc3986-validator        0.1.1
rich                     13.7.1
rsa                      4.9
safetensors              0.4.3
scanpy                   1.10.2
scikit-learn             1.4.2
scikit-misc              0.4.0
scipy                    1.9.3
scs                      3.2.4.post1
seaborn                  0.13.2
Send2Trash               1.8.0
session-info             1.0.0
setuptools               68.2.2
shellingham              1.5.4
six                      1.16.0
smart-open               7.0.4
sniffio                  1.3.0
soupsieve                2.4
spacy                    3.7.5
spacy-legacy             3.0.12
spacy-loggers            1.0.5
SQLAlchemy               1.4.47
srsly                    2.4.8
stack-data               0.6.2
statsmodels              0.14.2
stdlib-list              0.10.0
sympy                    1.13.0
tableone                 0.8.0
tabulate                 0.9.0
terminado                0.17.1
texttable                1.7.0
thefuzz                  0.22.1
thinc                    8.2.5
threadpoolctl            3.1.0
timeago                  1.0.16
tinycss2                 1.2.1
tokenizers               0.19.1
torch                    2.2.2
tornado                  6.2
tqdm                     4.66.4
traitlets                5.9.0
transformers             4.42.3
typeguard                4.2.1
typer                    0.12.3
typing_extensions        4.11.0
tzdata                   2024.1
ucimlrepo                0.0.3
umap-learn               0.5.6
uri-template             1.2.0
urllib3                  1.26.15
virtualenv               20.24.6
visions                  0.7.6
wasabi                   1.1.3
wcwidth                  0.2.6
weasel                   0.4.1
webcolors                1.12
webencodings             0.5.1
websocket-client         1.5.1
wheel                    0.38.4
widgetsnbextension       4.0.5
wordcloud                1.9.3
wrapt                    1.16.0
xgboost                  2.0.3
xxhash                   3.4.1
y-py                     0.5.9
yarl                     1.9.4
ydata-profiling          4.7.0
ypy-websocket            0.8.2

Can you help me to solve this?

**Comment by Zethson** [comment]
Ahh, this has been moved recently to a TYPE_CHECKING section. I've fixed this but have not made a release yet. Could you please try an older version of scanpy by running: `pip install scanpy==1.10.1`?

**Comment by safoora174** [comment]
> Ahh, this has been moved recently to a TYPE_CHECKING section. I've fixed this but have not made a release yet. Could you please try an older version of scanpy by running: `pip install scanpy==1.10.1`?

Thank you. I did that and got this error:
AttributeError: type object 'StackedViolin' has no attribute 'DEFAULT_SCALE'
Should I install an older version of ehrapy?
