### ISSUE TITLE
Unnecessary underscores in the documentation

### ISSUE THREAD

**Issue by VladimirShitov** [theislab/ehrapy#784]
### Report

It is not uncommon to see elements of code like this in the documentation:
```
_ = ep.tl.causal_inference(
    adata=adata,
    graph=causal_graph,
    treatment="aline_flg",
    outcome="icu_los_day",
    estimation_method="backdoor.linear_regression",
)
```

What is the point of having `_ = `? This is exactly what happens in Python internally, anyway. If this is done to prevent printing an output returned by the function, a much more elegant way would be to put `;` at the end of the line.

I'm pretty sure I asked this question already, but probably not on GitHub. Sorry for not remembering the answer 

### Version information

The current release of ehrapy at the time of writing is `0.8.0`

**Comment by Zethson** [comment]
> If this is done to prevent printing an output returned by the function, a much more elegant way would be to put ; at the end of the line.

Yeah, this is totally not elegant.

There is a third option which is to tag the cell with `hide-output` which is interpreted by most sphinx themes.

Will be fixed!

Thank you.
