### ISSUE TITLE
Pip install not working

### ISSUE THREAD

**Issue by alezenonos** [theislab/ehrapy#810]
### Report

ERROR: Could not find a version that satisfies the requirement ehrapy (from versions: none)
ERROR: No matching distribution found for ehrapy

**Comment by Zethson** [comment]
Dear @alezenonos,

please provide sufficient information for me to be able to help. What is your Python version? Your OS? The issue template asks for these things for a reason.

Thanks!

**Comment by alezenonos** [comment]
MacOS Sonoma, Python 3.6.3

**Comment by Zethson** [comment]
Yeah so Python 3.6.3 is ancient and not supported. It doesn't even get security updates anymore. Please use a more recent version of Python (3.10 or 3.11) in a virtual environment.
