### ISSUE TITLE
Make Survival Analysis Estimators consistent, and pass all required arguments

### ISSUE THREAD

**Issue by eroell** [theislab/ehrapy#822]
### Description of feature
1. consistency
E.g. tl.kmf operates on two arrays (see also #387) while tl.nelson_aalen operates on an anndata.
The latter should be the norm here if suitable.
2. passing all required arguments
Then, e.g. tl.weibull doesnt take the entry column or any way to pass this to the fitter; harmonizing this to ensure all flexibility offered by lifelines is userfacing would be a great enhancement!

**Comment by eroell** [comment]
Can also make a suitable checkpoint list here together if it helps!

**Comment by aGuyLearning** [comment]
- [ ] Update Readme in Notebooks to include an installation command for locally cloned repos
- [ ] make method signatures uniform and kwargs
- [ ] update notebook example using kmf
- [ ] update documentation

**Comment by eroell** [comment]
Trying to gather a few more detailed points, some might already be ticked off :)
- [ ] Remove `kmf` from the documentation, and raise deprecation warning when it is called anyways
- [ ] Add `kaplan_meier` as the new fitter (consistent with how the other fitters of survival analysis)
- [ ] Add new tests for `kaplan_meier`
- [ ] Remove kmf usage throughout the docs:
    - [ ] plot_kmf (here, a consider simple renaming to `plot_kaplan_meier`?), update its examples
    - [ ] tutorials

**Comment by eroell** [comment]
> Update Readme in Notebooks to include an installation command for locally cloned repos

@aGuyLearning if you're interested in adding this, feel free to do so in a new PR!
